### PR TITLE
[cc65] Fix and improvement of signed division with a constant denominator.

### PR DESCRIPTION
**Pull request by acqn**
This fixes Issue #169 and can optimize division with a negative power-of-2 constant denominator as well (as previously positive only) into shift according to the code size factor settings as below:
- positive power-of-2 denominator (> 1): code size factor >= 170.
- negative power-of-2 denominator (< -1): code size factor >= 200.

There are some new optimization steps (that are currently held back due to dependency on other changes) to improve both of the size and speed aspects.

### CODE REVIEW

**Comment by mrdudz** [comment]
Perhaps add the tests to this PR?

Awesome work you are doing with the compiler, please don't stop! :)

**Comment by oliverschmidt** [comment]
> Awesome work you are doing with the compiler, please don't stop! :)

Fullest possible ACK !

**Comment by polluks** [comment]
Next release will be the best cc65 ever :-)

**Comment by oliverschmidt** [comment]
Now that https://github.com/cc65/cc65/issues/1071 is sorted out we can move forward again.

**Pull request merged**
