### PR TITLE
Fix all chars 35, 38, 42, 47, 52, 13+64, 23+64, 31+64, 109+128, 119+128, 127+128 for issue #957

### LINKED ISSUE #957: [tgi][lynx][bug] Last column in characters is shown with black foreground color
The last column in characters is shown with black foreground color:
```c
#include "display_macros.h"
#include "graphics_settings.h"
#include <tgi.h>
#define CLI() asm("\tcli")
int main(void)
{
    tgi_install (tgi_static_stddrv);
    tgi_init ();        
    CLI();
    tgi_clear();
    while (tgi_busy())  {  };
    tgi_setpalette(tgi_getdefpalette());
    tgi_setbgcolor(TGI_COLOR_GREY);
    tgi_setcolor(TGI_COLOR_RED);
    tgi_outtextxy(8*6,8,"** ##"); 
    tgi_setcolor(TGI_COLOR_WHITE);
    tgi_outtextxy(8,8,"** ##"); 
    while(1){};
    return 0;
}
```
image

### PR DESCRIPTION
**Pull request by Fabrizio-Caruso**
Fixes #957.

### CODE REVIEW

**Comment by Fabrizio-Caruso** [comment]
This is a tentative fix for 5 out 11 characters for TGI for the Lynx target, namely `#,` `&,`  `*,` `/,` `4`.
The characters are now 8 rows x 7 columns.
@greg-king5 could you please take a look at it?
If it is ok for you, I can also adjust the remaining 6 characters.

In the attachments you see before and after fix effects:
before_fix
after_fix

**Comment by Fabrizio-Caruso** [comment]
Tested with:
```
#include <tgi.h>
#define CLI() asm("\tcli")
int main(void)
{
    tgi_install (tgi_static_stddrv);
    tgi_init ();        
    CLI();
    tgi_clear();
    while (tgi_busy())  {  };
    tgi_setpalette(tgi_getdefpalette());
    tgi_setbgcolor(TGI_COLOR_GREY);
    tgi_setcolor(TGI_COLOR_RED);
    tgi_outtextxy(8,8*1,"**"); 
    tgi_outtextxy(8,8*2,"##"); 
    tgi_outtextxy(8,8*3,"&&");
    tgi_outtextxy(8,8*4,"44");
    tgi_outtextxy(8,8*5,"//"); 
    tgi_outtextxy(8,8*8,"1234567890");
    while(1){};
    return 0;
}
```

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I may have fixed all characters. Only a minor imperfection in small and capital `m` and `n` letters, which start on column 0 instead of column 1. Nevertheless they all look good when used horizontally.

I think this is could be merged and improved later.

**Comment by greg-king5** [comment]
> Only a minor imperfection in small and capital `m` and `n` letters, which start on column 0 instead of column 1.

`M` and `W` usually are wider than other letters.  They and `N` look good  -- all of them look good to me!  Some of them (such as `#`) look better than they did before.  Serendipity.

I will merge this PR.

**Comment by Fabrizio-Caruso** [comment]
Thanks! :-)

**Pull request merged**
