### PR TITLE
Fix color 1 and 2 (grey/green levels)

### PR DESCRIPTION
**Pull request by Fabrizio-Caruso**
This new PR fixes color 1 and 2 (grey/green levels).
My previous fix only worked correctly with `COLOR_BLACK` , `COLOR_WHITE` (i.e., 0 and 3). 

I have introduce names for color 1 and 2 in a way that is consistent with what is done for the C64:
`COLOR_GRAY1`, `COLOR_GRAY2`. 

Even my games written with Cross-Lib now get 3 grey levels + background when compiled for the Gamate console.

Here some examples:
image
image
image
image
image
image

### CODE REVIEW

**Comment by polluks** [comment]
No executables in a repo please. Maybe we should add it to `.gitignore`.

**Comment by Fabrizio-Caruso** [comment]
> No executables in a repo please. Maybe we should add it to `.gitignore`.

Done in the last two commits.

**Comment by Fabrizio-Caruso** [comment]
@polluks @mrdudz All my games work fine. I have further tested the fix with the example below.
@mrdudz Could this fix be merged?
```
#include <conio.h>
#include <unistd.h>
#include <joystick.h>
#include <stdint.h>

void waitForJoy(void) {
    while(!(JOY_BTN_1(joy_read(0)))){};
}

void display_3_rows(uint8_t x_offset, uint8_t y_offset) {
    uint8_t i;
    uint16_t j;
    for(i=0;i<3;++i) {
        gotoxy(x_offset,y_offset+i);
        textcolor(1+i);
        cprintf("hello");
        for(j=0;j<10000;++j){};
        waitForJoy();
    }
}

int main(void) {
    uint8_t i;
    joy_install((void *)joy_static_stddrv);    
    while(1) {
        clrscr();
        for(i=0;i<3;++i) {
        display_3_rows(2+i,2+i);
        waitForJoy();
        }
        for(i=0;i<3;++i) {
        display_3_rows(2+5*i,9+i);
        waitForJoy();
        }
        sleep(1);
    }
    return 0;
}
```
which correctly produces this (after pressing the fire button multiple times):
image

**Comment by Fabrizio-Caruso** [comment]
@polluks @mrdudz Anything left to do for a merge?

**Comment by polluks** [comment]
Don't waste cycles ;-)
````
@delete1:
        lda   #$00
        sta   LCD_DATA
        iny
        bne @delete1
````
&rarr;
````
@delete1:
        lda   #$00
@L1:    sta   LCD_DATA
        iny
        bne @L1
````

**Comment by Fabrizio-Caruso** [comment]
@polluks Thanks! Done in the latest commit.

**Comment by Fabrizio-Caruso** [comment]
@polluks , @mrdudz  Guys, I have applied all suggested changes. If no other change or test is required, could we have this merged?

**Comment by mrdudz** [comment]
sure, thanks!

**Pull request merged**
