### PR TITLE
Apple2 SSC: Implement no flow control

### PR DESCRIPTION
**Pull request by colinleroy**

### CODE REVIEW

**Comment by oliverschmidt** [comment]
I must admit that I don't like the IRQ routine to become slower - especially in "default" code path.

My proposal is to "just" have RtsOff the bit %00001000 set when no handshake is desired. Then both the code asserting flow control in the IRQ routine and the code de-asserting flow control in the get routine just always "unnecessarily" write the same value into the register.

This allows you to remove the HsType variable again and use tmp2 until you get to the point where RtsOff is set.

**Comment by colinleroy** [comment]
Very good idea :)

**Comment by oliverschmidt** [comment]
You are right. I originally thought that the additional cycles would be spent on every interrupt. But you did it right in the first place: Only check for the handshake type type _after_ checking that flow control is desired.

**Comment by colinleroy** [comment]
Thank you @oliverschmidt!

**Pull request merged**
