### PR TITLE
Add STATUS definition

### PR DESCRIPTION
**Pull request by ops**
Added definition of STATUS ($90) for Commodore targets.

### CODE REVIEW

**Comment by spiro-trikaliotis** [comment]
Why? The KERNAL call READST accesses exactly that variable.

Of course, one could argue that this is faster. But then, we should also add the definitions to circumcent RDTIM, CLRCHN, CKOUT, CHKIN, SETLFS, SETNAM, and so on...

**Comment by ops** [comment]
Are you saying that there is never need to set STATUS value?

**Comment by polluks** [comment]
See https://github.com/cc65/cc65/blob/2646c06f61b46ed142bbefc723acb8c2113a23f9/libsrc/c64/crt0.s#L66

**Comment by oliverschmidt** [comment]
> Already done

@polluks: Once more ;-) I need to ask you to elaborate. Do you want to express that this pull request is not desirable (like @spiro-trikaliotis does) ?

**Comment by oliverschmidt** [comment]
@polluks: Now I happen to read your original comment https://github.com/cc65/cc65/pull/1352#issuecomment-735401836 referring to https://github.com/cc65/cc65/blob/2646c06f61b46ed142bbefc723acb8c2113a23f9/libsrc/c64/crt0.s#L66 so I understand your point. However, there could easily be a difference between cc65 code and user code. Therefore that fact that cc65 code writes to `STATUS` doesn't imply that user code is supposed to do that too. I as well-known CBM noob still have no clue, so I'm asking for additional comments.

**Comment by polluks** [comment]
"Already done" means we simply defined STATUS as ST.

**Comment by polluks** [comment]
@oliverschmidt You wrote "Turned the 'ST' status byte into a symbol resolved by the linker in order to allow to use it from code living in the 'cbm' directory."
ops didn't notice this commit message. User code should use READST anyway.

**Comment by mrdudz** [comment]
I am with spiro there - we have readst, and we can not be sure for certain that ST (not STATUS) is even $90 on all targets, with all kernals. Using the respective functions is exactly why they exist.

I also wonder what kind of code it is that wants to set ST - it seems this is a candidate for library code

**Comment by polluks** [comment]
@mrdudz nearly
https://github.com/cc65/cc65/blob/2646c06f61b46ed142bbefc723acb8c2113a23f9/libsrc/pet/status.s#L5

**Comment by mrdudz** [comment]
What is that supposed to tell me? This is library code.

Whatever, apparently those .inc files have all kind of things defined in them that fall into the same category, in that case i dont see a reason for why ST shouldnt be there.

**Comment by oliverschmidt** [comment]
Okay, my take: There seems to be no mystery about that ZP location. So if someone thinks he wants to access it directly there's nothing hindering him from doing so anyway. Therefore we can as well make the symbol available as a simple matter of convenience. Strong opposite opinions?

**Pull request merged**
