### PR TITLE
[cc65] Fixed ICE on error cases such as '&func + int a'.

### PR DESCRIPTION
**Pull request by acqn**
Fixed a regression introduced by PR #1424.

### CODE REVIEW

**Comment by oliverschmidt** [comment]
@mrdudz: Do you want to provide feeback on this PR from the test perspective?

**Comment by oliverschmidt** [comment]
No feedback for five days -> merging...

**Comment by mrdudz** [comment]
@acqn could you give a more specific hint on what was fixed here? i tried
```
#include <stdlib.h>

void f1(int n)
{
    return;
}

int a;
void *p;
void (*func)(int);

int test1(void)
{
    func = f1;
    p = &func + a;
    return 0;
}

int main(void)
{
    test1();
    return EXIT_SUCCESS;
}
```
and this compiles just fine using 1bd04e84

**Comment by mrdudz** [comment]
@acqn please?

**Comment by greg-king5** [comment]
In your test, `&func` is the address of a pointer variable.  His fix is for the (direct) address of a function:
```c
p = f1 + a;
p = f1 + 17;
```

**Comment by mrdudz** [comment]
Wtf? Once again i wonder.... why would you do this in the first place? :=)

**Comment by oliverschmidt** [comment]
You can reframe this as: "Good that it's __SUCH__ an obscure thing, that causes an ICE." ;-)

**Comment by mrdudz** [comment]
ok so i rewrote the test to this:
```
#include <stdlib.h>
#include <stdio.h>

void f1(void)
{
    return;
}

int a;
void *p;

unsigned long test1(void)
{
    p = f1;
    return (unsigned long)p;
}

unsigned long test2(void)
{
    a = 42;
    p = f1 + a;
    return (unsigned long)p;
}

unsigned long test3(void)
{
    p = f1 + 17;
    return (unsigned long)p;
}

unsigned long x, y, z;
int res = 0;

int main(void)
{
    x = test1();
    y = test2();
    z = test3();
    if ((y - x) != 42) {
        res++;
    }
    if ((z - x) != 17) {
        res++;
    }
    printf("res: %d\n", res);
    return res;
}
```
to my own surprise it does actually compile with gcc (tried --std=c89 and --std=c99). Only with --pedantic gcc produces a warning (but no error).

with cc65 it produces an error (but no ICE):
```
pr1442.c:22: Error: Invalid operands for binary operator '+'
pr1442.c:28: Error: Invalid operands for binary operator '+'
2 errors and 0 warnings generated.
```

That raises the question what the standard says to this :) do we expect an error or not? @acqn ?

**Comment by mrdudz** [comment]
@acqn Could you comment on this? What do we expect according to the standard - error? Warning? I'd like to add this test at the right place :)

**Pull request merged**
