### PR TITLE
DO NOT MERGE: Deliberately broke c file to test github actions pull request building.

### PR DESCRIPTION
**Pull request by dqh-au**

### CODE REVIEW

**Comment by dqh-github** [comment]
As things stand, the Github UI does not discourage me from merging this pull request.

To fix this, an admin of this repo needs to:

1. Click Settings
2. Click Branches on the left
3. Click Add rule on branch protection rules
4. put 'master' in the Branch name pattern
5. tick 'Require status checks to pass before merging'
6. in the search box just below, start typing 'Build and Test (Linux)' and add that when it pops up
7. as above, but with 'Build (Windows)'
8. Save changes

At this point, I believe users with regular commit access will not be able to merge a pull req unless the tests have passed. An admin will still be able to merge it, but will be discouraged from doing so.

**Comment by mrdudz** [comment]
OK, updated the settings as you said - please sync the branch in this PR with master so we can see what happens. Right now it even doesnt allow me to merge it (which is good!)

**Comment by dqh-au** [comment]
Testing complete - committers now can't merge broken pullreq, admins can with a warning. Deleting.

**Comment by greg-king5** [comment]
Unfortunately, that branch protection rule goes too far.  It doesn't limit itself to Pull Requests.  It won't let us push any commits to this repository!

I think that the rule should be canceled.

**Comment by dqh-au** [comment]
I have no opinion on how this project should be managed, but you could always create a pull request for your branch and merge it once the tests have passed? A lot of projects run this way, I think it’s probably the standard approach. Not a big price to pay for the improved stability brought by the regression test runs.

Best Regards,
Dave

**Comment by mrdudz** [comment]
Damn thats retarded. We need to be able to push to the main branch, indeed

**Comment by mrdudz** [comment]
I removed the rule - hopefully it will still run the tests at least and show a meaningful result

**Comment by greg-king5** [comment]
Pushing works as expected.  Keep in mind that the commits go through before the tests are started.  Therefore, if a test fails, then you still need to update your local repository before you work on a fix.

**Comment by mrdudz** [comment]
i dont understand what you are trying to say - before we didnt have CI for direct pushes at all. anything that is big enough of a change to justify using CI should always go via PR anyway.

**Comment by dqh-au** [comment]
I built two workflows. One for pull requests, and one for any commit to master. That’s the one that I’ll upgrade to make pre-releases on commit (like VICE).

Consider also that unless you configure GitHub to require that a pullreq have all of latest master merged on it at time of merge, it’s possible for pullreq tests to pass but when then combined with latest master, not pass. So it makes sense to re-test on merge.

Best Regards,
Dave

**Comment by greg-king5** [comment]
Even a trivial push could have a typo that breaks everything that comes later, even PRs.

**Comment by mrdudz** [comment]
Somehow that pushes me to requiring PRs for everything

**Comment by dqh-au** [comment]
In practice, it’s fine. Either work on a branch, or create one when you are ready to push. When you push the branch, the console will show the URL you need to use to create the pullreq. From there it’s convenient to review the diff before creating the pull req. If you enable auto-merge on the repo, you can set the PR to merge itself when the checks pass.

**Pull request closed without merging**
