### PR TITLE
[cc65] Added support for long-type bit-fields

### LINKED ISSUE #1131: [feature request] long bit-fields
Same as #1047 except for long. This requires slightly more code to be added.

### PR DESCRIPTION
**Pull request by acqn**
Resolved #1131.

Note:
> There is a design question with long bit-fields: how are they int-promoted?
> The rules listed below (which are also implemented in my current work) are borrowed from C++, and seem to be consistent with GCC/Clang's:
- If an `int` can represent all values of the bit-field, the bit-field is converted to an `int`;
- Otherwise, if an `unsigned int` can represent all values of the bit-field, the bit-field is converted to an `unsigned int`;
- Otherwise (that is with bit-width > 16), the bit-field will have _the **underlying integer type** (either `signed long` or `unsigned long`) as declared_.

### CODE REVIEW

**Comment by acqn** [comment]
Hmm, so what's with the failed target test?

**Comment by mrdudz** [comment]
THAT is a good question, it seems to randomly fail on that one, no idea why - you can click on details and rerun the jobs (i just did) and it will pass eventually

**Comment by mrdudz** [comment]
Please someone review, then we can merge

**Comment by acqn** [comment]
So... what is the label https://github.com/cc65/cc65/labels/co65 on this PR?

**Comment by mrdudz** [comment]
Its wrong :=) @greg-king5 @spiro-trikaliotis care to comment? :)

**Comment by spiro-trikaliotis** [comment]
I miss the test cases for this. Am I blind?

**Comment by mrdudz** [comment]
Oh, yes. Test would indeed be good

**Comment by acqn** [comment]
Oh yes. They were missing from the PR. Now I am integrating them with the existing bitfield testcases.

**Comment by acqn** [comment]
Testcase by a bug found in 'unsigned' vs 'long' comparisons.

**Comment by mrdudz** [comment]
Looks good to me, should we merge? :)

**Comment by mrdudz** [comment]
care to fix the conflict, please? :)

**Comment by acqn** [comment]
> care to fix the conflict, please? :)
Is there plan to merge this any time soon before yet another conflict occur?

**Comment by mrdudz** [comment]
Sure, if we have tests (which i think we have now?) no reason not to do it :)

**Comment by acqn** [comment]
Then just use my version of the conflicting file src/cc65/declare.c which I don't know how to do via the "Resolve conflicts" web interface on github. (Why? No access to my working copy.)

Feel free to remove the white space now relocated in src/cc65/initdata.c later.

**Comment by mrdudz** [comment]
OK - please confirm that what i did was the right thing :)

**Comment by polluks** [comment]
Maybe @acqn should become a repo admin because of commit quality.

**Comment by mrdudz** [comment]
> OK - please confirm that what i did was the right thing :)

so ? :)

**Comment by acqn** [comment]
> > OK - please confirm that what i did was the right thing :)
> 
> so ? :)

I changed my mind, manually edited the changes and force-pushed before I saw your post. I think this PR is fine at the moment.

**Comment by acqn** [comment]
> > OK - please confirm that what i did was the right thing :)
> 
> so ? :)

I changed my mind, manually edited the changes and force-pushed before I saw your post. I think this PR is fine at the moment.

**Comment by mrdudz** [comment]
done, thanks :)

**Pull request merged**
