### PR TITLE
Mark index 0 as TRANSPARENT. Let palette start from index 1

### PR DESCRIPTION
**Pull request by karrika**
#1584 proposed fix

### CODE REVIEW

**Comment by greg-king5** [comment]
Please update `"lynx/tgi_colors.s"`.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz Could this PR be merged? If not, what is missing?

**Comment by mrdudz** [comment]
A lost a bit track of this - do we have a test program for this thing now? As with other things, it would be good to have a portable test program that can be used to check (and compare) the output on different platforms to make sure its consistent.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I suppose we already have such test:
https://github.com/cc65/cc65/blob/master/samples/tgidemo.c

**Comment by mrdudz** [comment]
I was more thinking of something that uses more different text- and background colors... perhaps tgidemo can be expanded a bit to do that?

**Comment by karrika** [comment]
> I was more thinking of something that uses more different text- and background colors... perhaps tgidemo can be expanded a bit to do that?

The idea of bgcolour only exists in the Lynx. The concept is implemented with tgi_ioctl.

I may have added it in the early days as a way to print black. You were able to print black text on white paper this way.

**Comment by mrdudz** [comment]
> The idea of bgcolour only exists in the Lynx. The concept is implemented with tgi_ioctl.

TGI has no background color? OK (shows how often i use it =P)

merging then :)

**Pull request merged**
