### PR TITLE
support for the Creativision console

### PR DESCRIPTION
**Pull request by mrdudz**
this is basically the ages old PR from cvemu/master, including some more stuff by oliver. it still needs work (obviously, else it would already be merged back then)

i am putting it here for review... please let me know what is missing and still needs to be done - i havent looked closer at it myself yet... just saving it from getting lost in time.

if someone could hint me on what emulator can be used and how exactly (do i need a bios or so?) that would also help perhaps :)

### CODE REVIEW

**Comment by oliverschmidt** [comment]
I remember that the old pull request was closed because the original author wasn't interested in improving the code style. Check i.e. the inconsistent indentation in https://github.com/mrdudz/cc65/blob/creativision/libsrc/creativision/psg.s

**Comment by polluks** [comment]
You may take a look at http://www.madrigaldesign.it/creativemu/emulators.php
BTW I made a creativision.sgml

**Comment by mrdudz** [comment]
ah, thanks... will come back to this sooner or later (VICE stealing my spare time atm :=))

**Comment by groessler** [comment]
Conflicts with current "master". I've updated it locally on my branch.

Are there just code style issues which prevented the merge or is there more? I'd try to clean it up...

**Comment by mrdudz** [comment]
i still have not really looked at it, sorry - i think it was indeed mostly about codestyle though

**Comment by groessler** [comment]
I've cleaned it up locally. What's the procedure to update a "foreign" pull request? I cannot push to your github repo.
Should I create my own pull request instead?

**Comment by mrdudz** [comment]
no idea :) since i wont work on this in the near future... just make a pull request yourself :)

**Comment by groessler** [comment]
Ok. Created an alternative Pull Request (#374).

**Comment by mrdudz** [comment]
closing this in favour of #374

**Pull request closed without merging**
