### PR TITLE
cbm stuff from greggs pull request

### PR DESCRIPTION
**Pull request by mrdudz**
so this is just the CBM related stuff. did quick test with C64 and it seems OK

### CODE REVIEW

**Comment by mrdudz** [comment]
ok more testing.... 

c64: OK
vic20: OK (needs vic20-32k.cfg)
pet: OK
plus4: OK
c128: OK
cbm510: OK
cbm610: OK

TODO: make testprog also check cpeekcolor, cpeekrevers, cpeeks

**Comment by mrdudz** [comment]
ok, mostly working now.

TODO: fix cpeeks() for c128 (VDC)

please comment :)

**Comment by oliverschmidt** [comment]
> please comment :)

As far as I understand it it looks nice :-)

> TODO: fix cpeeks() for c128 (VDC)

Would you like to see this PR merged with that open TODO ?

**Comment by mrdudz** [comment]
> Would you like to see this PR merged with that open TODO ?

of course not, it is fixed :)

**Comment by mrdudz** [comment]
correction: it doesnt seem to work 100% yet ... so hold it back for now, i am in the process of making my old tetris thing compile with this stuff, that will allow for some more testing

**Comment by mrdudz** [comment]
i take everything back and claim the opposite. it works fine (bug was in the tetris thing :=))

so, feel free to merge!

**Comment by oliverschmidt** [comment]
Thanks for the - positive - feedback.

**Comment by mrdudz** [comment]
so? :)

**Comment by oliverschmidt** [comment]
So ... we're given the others a little time to comment your pull request before merging it - okay?

**Comment by mrdudz** [comment]
ausnahmsweise :o)

**Comment by mrdudz** [comment]
awesome! thanks

**Comment by oliverschmidt** [comment]
Thanks for the contribution !

**Pull request merged**
