### PR TITLE
[cc65] Fixed bitwise shift with numeric constant operand(s)

### PR DESCRIPTION
**Pull request by acqn**
- Fixed bitwise shift when the rhs is a numeric constant with side-effects.
- "Fixed" signed numeric constant bitwise shift when the result should overflow so that we always have 2's complement results.

### CODE REVIEW

**Comment by mrdudz** [comment]
Would be nice to have a test for this (which fails before and works after this fix)

**Comment by acqn** [comment]
Hmm, so what's with this test? It passes for me.

**Comment by spiro-trikaliotis** [comment]
Please note that some of the tested left-shifts are UB.
cf. n1256, 6.5.7 "Bitwise shift operators", clause 4:

"The result of E1 << E2is E1 left-shifted E2 bit positions; vacated bits are filled with
zeros. If E1 has an unsigned type, [...]. If E1 has a signed
type and nonnegative value, and E1 × 2^{E2} is representable in the result type, then that is
the resulting value; otherwise, the behavior is undefined."

Note that 0x8000 (signed 16 bit int) * 2 is not representable in signed 16 bit; thus, this is UB.

**Comment by acqn** [comment]
> Please note that some of the tested left-shifts are UB. cf. n1256, 6.5.7 "Bitwise shift operators", clause 4:
> 
> "The result of E1 << E2is E1 left-shifted E2 bit positions; vacated bits are filled with zeros. If E1 has an unsigned type, [...]. If E1 has a signed type and nonnegative value, and E1 × 2^{E2} is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined."
> 
> Note that 0x8000 (signed 16 bit int) * 2 is not representable in signed 16 bit; thus, this is UB.

True. But we can make the results always "2's complement" which is a legitimate outcome of UB.
And failing the test doesn't make sense according to cc65's implementation...

**Comment by mrdudz** [comment]
> But we can make the results always "2's complement" which is a legitimate outcome of UB.

That seems reasonable to me

> And failing the test doesn't make sense according to cc65's implementation...

Not sure if i understand this one - but to me it makes sense to also test if UB actually produces what we expect cc65 to produce. Perhaps add a comment explaining this in the test where needed

**Comment by spiro-trikaliotis** [comment]
> @spiro-trikaliotis does this look ok to you now? :)

Well, I did not have a detailed look into the implementation. I only wanted to say that this patch wants to achieve more than the standard asks a compiler to do.

Of course, we are free to use 2's complement implementation (who would not do so in the last 40 years?), so if it is an agreement to rely on it, I'm fine.

Again, I did not have a detailed look into the patch nor into the test cases, if they are enough. I doubt I will have much time to do so in the near future, so feel free not to wait on my "ok".

I do not have any objections, though.

**Comment by mrdudz** [comment]
good enough for me :)

**Pull request merged**
