### PR TITLE
Implement __sysremove for sim65

### PR DESCRIPTION
**Pull request by colinleroy**
This will allow using unlink()/remove() in sim65 programs
Use it to unlink fgets' test output file

### CODE REVIEW

**Comment by mrdudz** [comment]
Good idea - but this patch is broken :) the "jumptable" ends at $fff9 for a reason - $fffa is the NMI vector. So you'll have to put new functions at the top of the table (and adjust the base address of the table), not at the bottom :)

**Comment by mrdudz** [comment]
Oops wrong click :)

Also, perhaps add some comment(s) at strategic places that point out this ("$fffa-$ffff are the hardware vectors")

**Comment by polluks** [comment]
Who likes this proprietary jump table at all? How about using the well-defined DOS/65 for sim65's I/O?
http://www.z80.eu/dos65/DOS-65_System_Interface_Guide_A.pdf

**Comment by colinleroy** [comment]
> Oops wrong click :)
> 
> Also, perhaps add some comment(s) at strategic places that point out this ("$fffa-$ffff are the hardware vectors")

I fell in the trap, didn't notice that!
PR updated.

**Comment by polluks** [comment]
Maybe we can add some kind of segment for protection?
`VECTORS:  load = ROM,            type = ro,  start    = $FFFA;`

**Comment by mrdudz** [comment]
> Maybe we can add some kind of segment for protection? `VECTORS: load = ROM, type = ro, start = $FFFA;`

Makes sense - feel free to make a PR :)

**Comment by mrdudz** [comment]
Merging... thanks!

**Pull request merged**
