### PR TITLE
[cc65] Fixed compatibility checks on "pointer to pointer" vs "pointer to array" etc.

### LINKED ISSUE #1895: cc65: Compiler accepts assignments of incompatible types
The following assignment is accepted by cc65 but the types are incompatible:

```C
int main(void)
{
    int (*p)[3];
    int **q = 0;
    q = p;
    return 0;
}
```

p is a pointer to an array[3] of int.
q is a pointer to a pointer to int.

For comparison: 

```
$ gcc -Wall -o test test.c
test.c: In function ‘main’:
test.c:5:7: warning: assignment to ‘int **’ from incompatible pointer type ‘int (*)[3]’ [-Wincompatible-pointer-types]
    5 |     q = p;
      |       ^
```

### PR DESCRIPTION
**Pull request by acqn**
Fixed #1895.

### CODE REVIEW

**Comment by mrdudz** [comment]
what about adding the snippet from the bug report as a test for this one? (perhaps add one or two more variants?)

**Comment by acqn** [comment]
Hmm, the test won't be simple:
```c
#define CONCAT(a, b) CONCAT_impl_(a, b)
#define CONCAT_impl_(a, b) a##b

#define CMP_TYPES_1(A, B)\
    do {\
        A p; B q;\
        p = q;\
    } while (0)

#define CMP_TYPES_2(A, B)\
    do {\
        A p; B q;\
        v = v ? p : q;\
    } while (0)

#define DECL_FUNCS(A, B)\
    void CONCAT(foo_,__LINE__)(A); void CONCAT(foo_,__LINE__)(B);

#define CMP_TYPES_3(A, B)\
    do {\
        DECL_FUNCS(A,B);\
    } while (0)

void *v;

int main(void)
{
    typedef int (*p1)[3];              /* pointer to array */
    typedef int **q1;                  /* pointer to pointer */
    typedef int (**p2)[3];             /* pointer to pointer to array */
    typedef int ***q2;                 /* pointer to pointer to pointer */
    typedef int p3[1][3];              /* array of array */
    typedef int *q3[1];                /* array of pointer */
    typedef int const **p4;            /* pointer to pointer to const */
    typedef int **q4;                  /* pointer to pointer to non-const */
    typedef int (*p5[1])(int (*)(p1)); /* array of pointer to function taking pointer to function taking pointer to array */
    typedef int (*q5[1])(int (*)(q1)); /* array of pointer to function taking pointer to function taking pointer to pointer */

    /* Warnings */
    CMP_TYPES_1(p1, q1);
    CMP_TYPES_1(q1, p1);
    CMP_TYPES_1(p2, q2);
    CMP_TYPES_1(q2, p2);
    /* CMP_TYPES_1(p3, q3); */
    /* CMP_TYPES_1(q3, p3); */
    CMP_TYPES_1(p4, q4);
    CMP_TYPES_1(q4, p4);
    /* CMP_TYPES_1(p5, q5); */
    /* CMP_TYPES_1(q5, p5); */

    /* GCC/clang give warnings but cc65 gives errors */
    CMP_TYPES_2(p1, q1);
    CMP_TYPES_2(p2, q2);
    CMP_TYPES_2(p3, q3);
    CMP_TYPES_2(p4, q4);
    CMP_TYPES_2(p5, q5);

    /* Errors */
    CMP_TYPES_3(p1, q1);
    CMP_TYPES_3(p2, q2);
    CMP_TYPES_3(p3, q3);
    CMP_TYPES_3(p4, q4);
    CMP_TYPES_3(p5, q5);

    return 0;
}
```
The problem is that __all__ warnings/errors must be given in this test but I can't figure out how to check for that.

**Comment by mrdudz** [comment]
> The problem is that all warnings/errors must be given in this test (or the test fails) but I can't figure out how to check for that.

OK - i thought of something much simpler actually, one file per tested warning/error.

Have a look at the examples added in 44b2e4f3 - hopefully that tells you how to add the above test

**Comment by acqn** [comment]
Is it feasible to reuse the same source file for each test by pre-defining a corresponding macro (`DO_TEST_1_SUB_1_A`, `DO_TEST_1_SUB_1_B` etc.)?
```c
/* Test 1 suite */
#ifdef DO_TEST_1_SUB_1_A
#define TEST_1_SUB_1_A CMP_TYPES_1
#else
#define TEST_1_SUB_1_A BLANK
#endif

#ifdef DO_TEST_1_SUB_1_B
#define TEST_1_SUB_1_B CMP_TYPES_1
#else
#define TEST_1_SUB_1_B BLANK
#endif

#ifdef DO_TEST_1_SUB_2_A
#define TEST_1_SUB_2_A CMP_TYPES_1
#else
#define TEST_1_SUB_2_A BLANK
#endif

#ifdef DO_TEST_1_SUB_2_B
#define TEST_1_SUB_2_B CMP_TYPES_1
#else
#define TEST_1_SUB_2_B BLANK
#endif

#ifdef DO_TEST_1_SUB_4_A
#define TEST_1_SUB_4_A CMP_TYPES_1
#else
#define TEST_1_SUB_4_A BLANK
#endif

#ifdef DO_TEST_1_SUB_4_B
#define TEST_1_SUB_4_B CMP_TYPES_1
#else
#define TEST_1_SUB_4_B BLANK
#endif

#ifdef DO_TEST_1_SUB_5_A
#define TEST_1_SUB_5_A CMP_TYPES_1
#else
#define TEST_1_SUB_5_A BLANK
#endif

#ifdef DO_TEST_1_SUB_5_B
#define TEST_1_SUB_5_B CMP_TYPES_1
#else
#define TEST_1_SUB_5_B BLANK
#endif

/* Test 2 suite */
#ifdef DO_TEST_2_SUB_1
#define TEST_2_SUB_1 CMP_TYPES_2
#else
#define TEST_2_SUB_1 BLANK
#endif

#ifdef DO_TEST_2_SUB_2
#define TEST_2_SUB_2 CMP_TYPES_2
#else
#define TEST_2_SUB_2 BLANK
#endif

#ifdef DO_TEST_2_SUB_3
#define TEST_2_SUB_3 CMP_TYPES_2
#else
#define TEST_2_SUB_3 BLANK
#endif

#ifdef DO_TEST_2_SUB_4
#define TEST_2_SUB_4 CMP_TYPES_2
#else
#define TEST_2_SUB_4 BLANK
#endif

#ifdef DO_TEST_2_SUB_5
#define TEST_2_SUB_5 CMP_TYPES_2
#else
#define TEST_2_SUB_5 BLANK
#endif

/* Test 3 suite */
#ifdef DO_TEST_3_SUB_1
#define TEST_3_SUB_1 CMP_TYPES_3
#else
#define TEST_3_SUB_1 BLANK
#endif

#ifdef DO_TEST_3_SUB_2
#define TEST_3_SUB_2 CMP_TYPES_3
#else
#define TEST_3_SUB_2 BLANK
#endif

#ifdef DO_TEST_3_SUB_3
#define TEST_3_SUB_3 CMP_TYPES_3
#else
#define TEST_3_SUB_3 BLANK
#endif

#ifdef DO_TEST_3_SUB_4
#define TEST_3_SUB_4 CMP_TYPES_3
#else
#define TEST_3_SUB_4 BLANK
#endif

#ifdef DO_TEST_3_SUB_5
#define TEST_3_SUB_5 CMP_TYPES_3
#else
#define TEST_3_SUB_5 BLANK
#endif

/* Implementation */
#define CONCAT(a, b) CONCAT_impl_(a, b)
#define CONCAT_impl_(a, b) a##b

#define BLANK(...)

#define CMP_TYPES_1(A, B)\
    do {\
        A p; B q;\
        p = q;\
    } while (0)

#define CMP_TYPES_2(A, B)\
    do {\
        A p; B q;\
        v = v ? p : q;\
    } while (0)

#define DECL_FUNCS(A, B)\
    void CONCAT(foo_,__LINE__)(A); void CONCAT(foo_,__LINE__)(B);

#define CMP_TYPES_3(A, B)\
    do {\
        DECL_FUNCS(A,B);\
    } while (0)

static void *v;

typedef int (*p1)[3];              /* pointer to array */
typedef int **q1;                  /* pointer to pointer */
typedef int (**p2)[3];             /* pointer to pointer to array */
typedef int ***q2;                 /* pointer to pointer to pointer */
typedef int p3[1][3];              /* array of array */
typedef int *q3[1];                /* array of pointer */
typedef int const **p4;            /* pointer to pointer to const */
typedef int **q4;                  /* pointer to pointer to non-const */
typedef int (*p5)(int (*)(p3));    /* pointer to function taking pointer to function taking pointer to array */
typedef int (*q5)(int (*)(q3));    /* pointer to function taking pointer to function taking pointer to pointer */

int main(void)
{
    /* Warnings */
    TEST_1_SUB_1_A(p1, q1);
    TEST_1_SUB_1_B(q1, p1);
    TEST_1_SUB_2_A(p2, q2);
    TEST_1_SUB_2_B(q2, p2);
    /* TEST_1_SUB_3_A(p3, q3); */
    /* TEST_1_SUB_3_B(q3, p3); */
    TEST_1_SUB_4_A(p4, q4);
    TEST_1_SUB_4_B(q4, p4);
    TEST_1_SUB_5_A(p5, q5);
    TEST_1_SUB_5_B(q5, p5);

    /* GCC and clang give warnings while cc65 gives errors */
    TEST_2_SUB_1(p1, q1);
    TEST_2_SUB_2(p2, q2);
    TEST_2_SUB_3(p3, q3);
    TEST_2_SUB_4(p4, q4);
    TEST_2_SUB_5(p5, q5);

    /* Errors */
    TEST_3_SUB_1(p1, q1);
    TEST_3_SUB_2(p2, q2);
    TEST_3_SUB_3(p3, q3);
    TEST_3_SUB_4(p4, q4);
    TEST_3_SUB_5(p5, q5);

    return 0;
}
```

**Comment by mrdudz** [comment]
> Is it feasible to reuse the same source file for each test by pre-defining a corresponding macro

You can always have seperate files (which then define a macro, or whatever) that include such common file - defining macros on the compiler cmdline would make the makefile a bit overcomplicated

**Comment by acqn** [comment]
Like these?
[typecompat.zip](https://github.com/cc65/cc65/files/9972792/typecompat.zip)
(which each simply define the corresponding macro and include the same "common source file")

Well, I know if I just put these directly under test/err, they could work (with additional `-Werror` cflag perhaps). But I suppose it would be better to add a subdirectory under test/err for grouping these tests, as we might have more "separate-file tests" like these someday.

**Comment by mrdudz** [comment]
mmmmh. I'd have them in the same dir, but all files using the same prefix (eg bug1895-) to group them together... subdirectories are a good idea in theory, but will also make the makefile more complex, and i'd like to avoid this right now. we can always still go this route once the number of tests become a problem.

**Comment by acqn** [comment]
Done.

**Comment by mrdudz** [comment]
Thanks!

**Pull request merged**
