### PR TITLE
[cc65] Code label reference fix

### PR DESCRIPTION
**Pull request by acqn**
Fixed Issue #897 and https://github.com/cc65/cc65/issues/1209#issue-683818702. The other issue reported in https://github.com/cc65/cc65/issues/1209#issuecomment-678738971 is not fixed yet.

### CODE REVIEW

**Comment by oliverschmidt** [comment]
@mrdudz: Do you want to create some test(s) before I merge this one?

**Comment by oliverschmidt** [comment]
No feedback in four days + turning an existing test case -> merging...

**Comment by mrdudz** [comment]
Sorry, busy with other stuff atm - i will add tests for this one and #1442 later if needed

**Comment by oliverschmidt** [comment]
> busy with other stuff atm

I see. Thanks for the feedback.

> i will add tests for this one and #1442 later if needed

More tests are always welcome ;-)

**Pull request merged**
