### PR TITLE
smarter manufacturer

### PR DESCRIPTION
**Pull request by polluks2**
some kind of promotion

### CODE REVIEW

**Comment by mrdudz** [comment]
Wouldnt it make more sense to have some external object that the user can replace as needed?

**Comment by mrdudz** [comment]
I am not convinced this is better, sorry. Especially since it is using the known broken CC65 version symbol :)

IMHO the string should simply be blank by default, and there should be a way to override it with an external symbol.

**Comment by greg-king5** [comment]
> I am not convinced this is better, sorry. Especially since it is using the known broken CC65 version symbol. :)

Then, don't use the version -- just `"cc65"`.
> 
> IMHO, the string should simply be blank by default, and there should be a way to override it with an external symbol.

I don't think that it can be done for a string literal.

**Comment by mrdudz** [comment]
> I don't think that it can be done for a string literal.

why not? just have it in a seperate object and then link it - just like we do with other things that can be replaced by the user

**Comment by mrdudz** [comment]
merging this, since the version symbol is fixed now

**Pull request merged**
