### PR TITLE
Fix sector-number conversions in the CBM GEOS DIO code.

### PR DESCRIPTION
**Pull request by greg-king5**
These fixes were sitting on my hard drive for about two and a half years!

[ I found those bugs while writing code for a CBM DIO implementation -- also two and a half years old. :-/ ]

### CODE REVIEW

**Comment by oliverschmidt** [comment]
Thanks :-)

**Comment by oliverschmidt** [comment]
> I found those bugs while writing code for a CBM DIO implementation -- also two and a half years old. :-/

Is there enough of that code present that others could benefit from it - or do you consider to complete it "now"?

**Comment by greg-king5** [comment]
I want to add a few things to my CBM DIO code; then, I'll put it in my public Github repository, so that others can see my design choices.

Also, I need to change `dio_open()`.  Currently, it uses the same zero-origin drive numberring system that other platforms use.  But, you want it to be compatible with the getdevice functions (which use Commodore's "eight-origin" device numbers).

**Comment by oliverschmidt** [comment]
> it uses the same zero-origin drive numberring system that other platforms use.

The Apple II DIO always used a getdevice functions compatible numbering. I think the zero-origin numbering wasn't a fortunate design decision anyway as it would never be clear if the numbering would only include the actual attached drives or also include potentially attached drives.

**Comment by oliverschmidt** [comment]
> I want to add a few things to my CBM DIO code; then, I'll put it in my public Github repository, so that others can see my design choices.

Do you have an estimate when this will be done?

**Comment by greg-king5** [comment]
> I want to add a few things to my CBM DIO code; then, I'll put it in my public Github repository, so that others can see my design choices.

It's published at https://github.com/greg-king5/cc65/tree/cbm-dio.

**Comment by oliverschmidt** [comment]
Thanks !

**Pull request merged**
