### PR TITLE
[cc65] Fixes for some opt bugs

### LINKED ISSUE #167: equality comparison is evaluated wrong in some cases
Here is an example that demonstrates the behaviour:

``` c
    #include <stdio.h>
    #include <stdint.h>

    int main ( void)
    {
      uint8_t  joy_state = 0x7e;
      printf("bad: %u\n", 0 == (joy_state & 1) );
      printf("good: %u\n", (joy_state & 1) == 0 );

      return 0;
    }
```

This results in:

```
bad: 0
good: 1
```

http://www.cc65.org/mailarchive/2014-10/11680.html

### PR DESCRIPTION
**Pull request by acqn**
Fix <s>#167 (dropped),</s> #971 and #992.

Edit: Also fixed the bug in #337.

### CODE REVIEW

**Comment by acqn** [comment]
So it's the yaccdbg.c test that failed. I'll see what's wrong with it.

**Comment by acqn** [comment]
For whatever reasons I couldn't make the fixed commit for #167 into this PR (I am using Mercurial)... Maybe I'd just drop that in this PR for now.

**Comment by oliverschmidt** [comment]
@acqn: First of all thanks for all the effort you put in cc65 so far. Fixing bugs is not the most funny thing to do ;-)

> Edit: I've made the fix for #167 and #784 (and maybe #781 as a side effect). Should I append that to this PR or wait for a new one?

I'm not sure what you refer to with "wait". I presume you are aware that you can send several pull requests simultaneously. You just need to make sure that each pull request refers its own branch in your fork.

**Comment by oliverschmidt** [comment]
I must admit that I'm having a pretty hard time to review this PR.

It's always the same with bugs in the optimizer:

Often proposed changes make the optimizer "weaker" by not applying a certain optimization in a certain scenario. Is it appropriate to consider those changes as fixes or are they rather workarounds? I mean, completely deactivating the optimizer would for sure make all bugs related to it go away ;-) So the question is if it was plainly wrong to try a certain optimization in a certain scenario in the first place (then not doing it would be a true fix) or if the optimization is rather conceptually correct but was "just" done in a wrong way (then not doing it would only be a workaround).

I see only two ways to approach this right:

- Understand enough of the cc65 optimizer to assess the fix vs. workaround aspect.
- Test cc65 in several complex scenarios not only for functionality but also for speed and size of the generated code in order to be able to assess the speed loss and/or code size increase in real world scenarios.

Unfortunately I personally am certainly unable to invest the time necessary for one way or the other :-(

Therefore I'm asking for advice on how to proceed with changes like the ones proposed here!

In case nobody comes up with help I'd tend to ask @acqn to mark his changes in the optimizer with hints to the "fixed" issue thus at least potentially helping someone to re-assess the changes later like this:

```
/* Fix for GitHub issue <issue URL> */
<new code>
/* Was: <old code> */
```

Or am I totally missing the point here(?)

Oliver

**Comment by polluks** [comment]
Indeed, the optimizer acts like like a mobile. Maybe we need more unit testing?

**Comment by mrdudz** [comment]
> Maybe we need more unit testing?

is that a question? :)

**Comment by oliverschmidt** [comment]
Okay, today I found some time to play with this PR:

* I could not find any negative side effect on the effectiveness of the optimizer.
* I could confirm that the issues https://github.com/cc65/cc65/issues/337, https://github.com/cc65/cc65/issues/971 and https://github.com/cc65/cc65/issues/992 are fixed.

From that perspective it seems appropriate to consider this PR as true fix and therefore merge it as-is.

@acqn: Thanks for providing the PR and sorry for the delay in processing!

**Comment by polluks** [comment]
@oliverschmidt How about closing these issues including #167?

**Comment by oliverschmidt** [comment]
First of all thanks for reminding me on the necessary cleanup.

I have closed https://github.com/cc65/cc65/issues/337, https://github.com/cc65/cc65/issues/971 and https://github.com/cc65/cc65/issues/992 as I had confirmed their fix back in Februar.

However, I didn't check https://github.com/cc65/cc65/issues/167 as the original message said "Fix <s>#167 (dropped),</s>". Therefoe I personally can't confirm it being fixed. Do you have a clear understanding of the current state of https://github.com/cc65/cc65/issues/167? If yes, please elaborate.

**Comment by polluks** [comment]
The fork https://github.com/acqn/cc65/commit/b6104e447644861811f3655a8bd005ccf69a49f1 seems to contain a 167 fix, but there's no PR. However it's @mrdudz issue...

**Comment by mrdudz** [comment]
? what's "my issue" there?

**Comment by oliverschmidt** [comment]
@polluks: Now you lost me...

First you write:

> How about closing these issues including #167?

This seems to imply that #167 should be closed now. But then you write:

> The fork acqn@b6104e4 seems to contain a 167 fix, but there's no PR.

This pretty much implies that #167 should not be closed now. Can please try to provide a conclusive statement on your perspective?

**Comment by polluks** [comment]
@oliverschmidt I didn't notice the patch is not part of the trunk and @acqn seems be to inactive :-(
@mrdudz #167 is your baby ;-)

**Comment by mrdudz** [comment]
aaah i just clicked on https://github.com/acqn/cc65/commit/b6104e4 and wondered wth its about :)

**Comment by oliverschmidt** [comment]
@polluks: Thanks for the clarification. So from my understanding all relevant issues are now in the state that correctly reflects the current code in this repo.

**Pull request merged**
