### PR TITLE
Fix for #1941

### LINKED ISSUE #1941: [bug] Shifts by zero bits are broken
I am assuming that right-shifing an unsigned char should have no effect on an unsigned char. This is the case in my code when compiled with any compiler except CC65.

I have this macro:
```
#define initial_letter_drop() \
do \
{ \
    uint8_t i; \
    uint8_t k; \
    \
    _XL_PRINTD(0,1,3,(uint8_t) MIN_INITIAL_DROP + (level>>0)); \
    k = MIN_INITIAL_DROP + (level>>0); \
    _XL_WAIT_FOR_INPUT(); \
    for(i=0;i<(uint8_t) MIN_INITIAL_DROP + (level>>0);++i) \
    { \
        drop_letter(); \
        short_pause(); \
    } \
} while(0)
```
It produces a infinite loop when compiled with CC65. It can be fixed if I use `k` instead of `(uint8_t) MIN_INITIAL_DROP + (level>>0)`.

I will try to reproduce it with a minimal example.

Has any recent commit changed how the right shift operator works?

### PR DESCRIPTION
**Pull request by laubzega**
Fixes #1941 by making sure the expression type remains unchanged if shift of 0 bits is requested.

### CODE REVIEW

**Comment by mrdudz** [comment]
It would be super nice if you would add a test for this problem to the PR

**Comment by acqn** [comment]
The result of shift-by-zero shall always be integer-promoted, or things like this would fail:
https://github.com/cc65/cc65/blob/22d435b68966b86929d3c393f3bbc1593b261cee/test/val/bug1941-shift-by-zero.c#L10

**Comment by mrdudz** [comment]
So the proposed fix needs a fix, i guess :)

**Comment by laubzega** [comment]
@acqn - would you be so nice and merge our PRs? Unless it can wait a few days (I am traveling rn).

**Comment by mrdudz** [comment]
what is missing here? do we basically want to merge https://github.com/acqn/cc65/commit/22d435b68966b86929d3c393f3bbc1593b261cee ? :)

**Comment by mrdudz** [comment]
ping? :)

**Comment by mrdudz** [comment]
@acqn @laubzega please comment, i can do whatever needs to be done, but i need to know what exactly :)

**Comment by mrdudz** [comment]
@acqn @laubzega PING! are you still on vacation or something? :)

**Comment by mrdudz** [comment]
@acqn @laubzega i took the patch from acqn and made a new PR #1983 - please check/test/confirm ;)

**Pull request closed without merging**
