### PR TITLE
Smaller driver code

### PR DESCRIPTION
**Pull request by polluks**

### CODE REVIEW

**Comment by greg-king5** [comment]
I suspect that the original code was `jmp EXIT`.  But then, it was replaced by that inline exit code, in order to gain a little extra speed (and, re-enable interrupts a few cycles sooner).

**Comment by oliverschmidt** [comment]
@greg-king5: Should I interpret your comment as rather not wanting to see this pull request merged?

**Comment by polluks** [comment]
At least EXIT should removed.

**Comment by greg-king5** [comment]
Yes, I think that the code path should keep its directly inlined exit instructions.

Stefan's advice about the EXIT label is wise, IMHO.

**Comment by oliverschmidt** [comment]
Thanks for coming to an agreement, gentlemen :-)

**Pull request merged**
