### PR TITLE
Lynx cc65 and ca65 include file improvements for Mikey and Suzy

### PR DESCRIPTION
**Pull request by alexthissen**
This set adds enumeration values and new structures to both _suzy.h and _mikey.h

Suzy changes:
- Math structures for accessing signed and unsigned multiply and divide
- New union for different ways to access math registers depending on operation
- Compatible enumerations for sprites, math and hardware registers

Mikey changes:
- New vectors struct for CPU vectors
- Compatible enumerations for timers, hardware registers (including test registers)

It also adds new definitions in ca65 include lynx.inc.
- Definitions for bit flags in lynx.inc for Suzy and Mikey
- Timer offsets for 8 Mikey timers

### CODE REVIEW

**Comment by mrdudz** [comment]
Looks ok - however, please use C style comments only

**Comment by alexthissen** [comment]
Before closing, please hold till I investigate order of writes for short and long first. This is important and it seems to be different for local variables and literal values. That would break the structs in Suzy math.

**Comment by mrdudz** [comment]
> Before closing, please hold till I investigate order of writes for short and long first. This is important and it seems to be different for local variables and literal values. That would break the structs in Suzy math.

You can not rely on that, the compiler can freely choose any order - so if that kind of thing is important, you really need to write the respective code in assembly.

That said, please fix the comments so this can be merged. Also please do not shuffle around stuff in header files and remove existing comments for no reason - ie produce the minimal diff.

**Comment by alexthissen** [comment]
Removed the structures and the corresponding union from the Suzy structure definition. 
Cleaned up, so ready for final check and approval.

**Comment by mrdudz** [comment]
> Removed the math structures and the corresponding union from the Suzy structure definition. Cleaned up, so ready for final check and approval.

There are still a bunch of c++ style comments - please use regular c-style comments instead

Also, a large portion of the diff apparently covers formatting changes and typo fixes - this makes the diff very hard to read, ie to see what was actually fixed or added. Next time please keep changes to a minimum - and IF you want to do style/formatting/typo fixing, please use a separate PR for just that (ie don't mix with actual code changes).

**Comment by alexthissen** [comment]
Changed to C-style comments.
Will separate typographic and grammatic errors separately next time.

**Comment by mrdudz** [comment]
> Changed to C-style comments.

thansk - you missed a few however (_mikey.h), please check those :)

**Comment by alexthissen** [comment]
Do you mean the end of line comments? That was already used (in this and other places) before I submitted the PR.

**Comment by mrdudz** [comment]
> Do you mean the end of line comments?

yes indeed

> That was already used (in this and other places) before I submitted the PR.

oh well, i see. i only see the diff of course. Still, please change them in the file(s) you touched, please

**Comment by mrdudz** [comment]
Thanks!

**Pull request merged**
