### PR TITLE
Fix minor preprocessor problems

### PR DESCRIPTION
**Pull request by kugelfuhr**
This PR fixes both issues from #2515.

I would have also added a test which was already written, but there seems to be no simple way to execute it in a way that works with the current test infrastructure.

### CODE REVIEW

**Comment by mrdudz** [comment]
Thanks!

would you post the test anyway? I'll try adding it in misc then

**Comment by kugelfuhr** [comment]
This test file

```c
#line 13"x"
#define X"y"
int main() { foo; }
```
generates 
```
test.c:1: Error: #line directive requires a simple decimal digit sequence
test.c:3: Error: Undeclared identifier 'foo'
2 errors and 0 warnings generated.
```

before the fix. After the fix, the output depends on the `--standard` setting. With no standard or `--standard c89` it generates

```
x:14: Error: Undeclared identifier 'foo'
1 errors and 0 warnings generated.
```

while it says 

```
x:13: Warning: ISO C99 requires whitespace after the macro name
x:14: Error: Undeclared identifier 'foo'
1 errors and 1 warnings generated.
```

using `--standard c99`.

**Comment by mrdudz** [comment]
Oh this is a tricky one :)

**Comment by mrdudz** [comment]
added the test in https://github.com/cc65/cc65/commit/7dc09fdb05051de5273abb83679924b7b265a680

**Pull request merged**
