### PR TITLE
g_asr, g_asl: Use ROL/ROR for char shifts >= 6

### PR DESCRIPTION
**Pull request by jmr**
Instead of `val` right shifts, we can also do `8 - val` left rotates and
a mask.  This saves 4 instructions for `val == 7` and 1 instruction for
`val == 6`.

### CODE REVIEW

**Comment by greg-king5** [comment]
You should count bytes and cycles (not instructions) when comparing new code versus old code.
The new code is worse for `val == 6`.  Only `val == 7` can benefit from it.

**Comment by jmr** [comment]
I think what I wrote was correct, since all instructions involved are two cycles. You're right that it was more bytes for `val == 6`.

I've now rewritten it to be better for both 6 and 7, and included the byte and cycle counts.

**Comment by oliverschmidt** [comment]
I think https://github.com/cc65/cc65/issues/1320 needs to be fixed before merging any other compiler-related PR.

**Comment by IrgendwerA8** [comment]
Haven't examined the code in-depth, but wouldn't just clearing the carry (CLC) before rotation save another byte as you don't need the AND then?

**Comment by oliverschmidt** [comment]
See https://github.com/cc65/cc65/pull/1331#issuecomment-735424994.

**Comment by IrgendwerA8** [comment]
Now, where those mentioned issues are closed, what about merging this one?

**Comment by oliverschmidt** [comment]
@greg-king5: Do you want to have another look at this PR or is just "everybody" waiting for me to merge?

**Pull request merged**
