### PR TITLE
[cc65] Fixed deferred post-inc and post-dec in unevaluated context

### PR DESCRIPTION
**Pull request by acqn**
This fixes the bug:
```c
#include <stdio.h>

int main(void)
{
    char i = 0;
    sizeof(i++);
    0 && i++;
    1 || i++;
    printf("%d\n", i);
    return i;
}
```
Expected output: `0`
Revision 131f96eb1eda192623b1b3e323a2a0739645b641 output: `3`

### CODE REVIEW

**Comment by mrdudz** [comment]
Why not add this test program as an actual test program? :)

**Comment by oliverschmidt** [comment]
Do I understand it right that the bug fixed here wasn't recorded as an issue so far?

**Comment by mrdudz** [comment]
> Do I understand it right that the bug fixed here wasn't recorded as an issue so far?

sounds like it :)

I'd add the test - but in this case it will only create extra work IMHO, easier to add it together with the fix :)

**Comment by acqn** [comment]
Testcase added.

**Comment by oliverschmidt** [comment]
My gut feeling is that this PR doesn't require more time to wait for potential feedback. Please let me know if you consider my assessment is inappropriate. However, for now: Merging...

**Pull request merged**
