### PR TITLE
Avoid infinite loops in ca65 that are caused by circular references.

### LINKED ISSUE #1651: ca65: Assembler hangs completely on certain input
The following input makes the assembler hang with 100% CPU load:

```
        S1      = S2
        S2      = S1
        lda     #S1
```

Please let know if more information or a patch is required.

### PR DESCRIPTION
**Pull request by greg-king5**
Fixes #1651.

### CODE REVIEW

**Comment by mrdudz** [comment]
before you fix the test procedure again, please make a bug report for the issue that makes it fail :) looks like cl65 screws it up somehow

**Comment by mrdudz** [comment]
Eh it worked now? Did you just re-run it? *shrug*

**Comment by greg-king5** [comment]
> Eh, it worked now? Did you just re-run it? _shrug_

Yep!  I changed nothing.  I merely re-ran the checks three times.  All worked.  The failure was a fluke.

**Comment by mrdudz** [comment]
Weird! regarding this PR - it would be nice to have a test for this issue

**Comment by mrdudz** [comment]
> A regression would hang the assembler. The test run couldn't finish!

Well, thats fine, isnt it? Working case would work, regression will break the testbench - thats all we want

**Pull request merged**
