### PR TITLE
let clrscr() make use of _bzero() (-17 bytes + 20% speed)

### PR DESCRIPTION
**Pull request by IrgendwerA8**
Optimization for Atari-"clrscr()"

### CODE REVIEW

**Comment by groessler** [comment]
Hmm, I don't see the "-17bytes" point.

```
#include <conio.h>
#include <atari.h>

int main(void)
{
  clrscr();
  return(0);
}
```

Old cc65:

`-rw-r--r-- 1 chris chris   660 Aug  3 01:56 clrscrtest.com`

Your branch:

`-rw-r--r-- 1 chris chris   758 Aug  3 01:59 clrscrtest.com`

Is "+98" bytes....

**Comment by polluks** [comment]
At least you gain space if you also use bzero, memset etc.

**Comment by IrgendwerA8** [comment]
Yes, the "-17 bytes" refers to an already used "bzero"/"memset".
Somehow I thought "bzero()" is already in charge for clearing BSS.
If I "fix" that in "zerobss.s" too, the 758 bytes will go down to 733.

Personally the number of programs I created without using "bzero"/"memset" tend to zero - so for me the changes would result in a gain, but I could understand if the mileage of others vary.
Opinions / comments?

**Comment by mrdudz** [comment]
I'm not familiar with the atari library... but how likely is it to write a non trivial program that would not pull in bzero?

**Comment by groessler** [comment]
@mrdudz, I cannot really assess this. bzero/memset might be used, or might not be used. I think it's not directly related to the triviality of the program.

**Comment by groessler** [comment]
I was a bit reluctant for this PR since the Atari lib is already quite large (runtime memory consuming). But with PR2484 I'm fine with the change. Please also change it for atari5200.

**Comment by Marrin** [comment]
This depends on what you mean by `' '` and `'\0'`.  The video memory doesn't expect ASCII or ATASCII but an [internal encoding for the characters](https://www.atariarchives.org/mapping/appendix10.php).  Similar to Commodore machines with the difference between PETSCII and screen codes.

**Comment by mrdudz** [comment]
I am leaning towards not merging this - is speed really an issue with clrscr() at all?

**Comment by IrgendwerA8** [comment]
For me it's not - but AFAIR for @groessler it is.
Otherwise the code would just consist in an output of CHR$(125) (clear screen) and would also work with 80 column drivers etc.

Since size is always an issue for me, I thought reducing the double/triple implementations is a good idea. (To make 'big' programs with 'bzero' not unnecessary even bigger.)
But of course I understand different motivations, too.

**Comment by groessler** [comment]
clrscr() in its current form is not there because of speed, but because it's part of conio. Mixing conio and rom functions is officially not supported.
You can always "putc" or "write" the 125 char on your program to clear the screen without linking in clrscr.

**Comment by IrgendwerA8** [comment]
Thanks for pointing out!

**Comment by groessler** [comment]
Interesting. I don't find it in the docs that conio and "regular" screen output shouldn't be mixed. But I remember it was for all targets, not just Atari.

**Comment by mrdudz** [comment]
It also applies to C64 (and all other CBM machines)... yes some conio functions use the kernal... however, not all operations work the same and it will start to behave strange sooner or later.

Someone might want to add a note to the docs if its not there :)

**Pull request closed without merging**
