### PR TITLE
helloworld ASM CBM Demo

### PR DESCRIPTION
**Pull request by netpipe**
Hello World for C64 CBM Assembly with makefile

### CODE REVIEW

**Comment by mrdudz** [comment]
*sigh* This is now the 3rd incarnation of PR #2391 - please stop making new PRs for the same thing. If you need to change/update a PR, commit into that very branch.

That said, while some issues of the original PR have been fixed, some others still stand:

* it first uses a kernal call to clear the screen (in a way that is technically broken), this needs to be fixed
* then copies the text to screen memory, in a non portable (c64 specific) way - why not use a kernal call for that as well?
* it right now lives in the cbm directory, but it is c64 specific
* its not added to the samples disk image

And last not least, as said before, the samples directory IMHO is for examples that show how to use the C compiler - and perhaps for some more advanced assembler things that are ca65 specific. I am not convinced that this kind of program even belongs there at all.

@oliverschmidt @groessler et al - what do you think?

**Comment by oliverschmidt** [comment]
I have no desire to have this program be part of cc65.

**Comment by groessler** [comment]
I also don't see the need for it

**Comment by mrdudz** [comment]
Agreed, case closed

**Pull request closed without merging**
