### PR TITLE
Fixed documented return type.

### PR DESCRIPTION
**Pull request by Marrin**

### CODE REVIEW

**Comment by oliverschmidt** [comment]
The GitHub WebUI doesn't allow me to merge this - without any error message. Does anybody know what's wrong?

**Comment by oliverschmidt** [comment]
A merge commit worked ?!?

**Comment by greg-king5** [comment]
> The GitHub WebUI doesn't allow me to merge this -- without any error message. Does anybody know what's wrong?

Do you remember what the error message said?

**Comment by oliverschmidt** [comment]
@greg-king5: First of all thanks for your interest.

As I wrote, there was no error message at all. The WebUI is a two step process:

1. Select between rebase, squash and merge
2. Confirm

My experience was that on step 2.) I was just returned before step 1.) without any message whatsoever. I tried it over some time period and with a fresh browser session.

But when I switched on step 1.) from rebase to merge everything worked as expected.

**Pull request merged**
