### PR TITLE
static driver

### PR DESCRIPTION
**Pull request by polluks**

### CODE REVIEW

**Comment by oliverschmidt** [comment]
Maybe a misunderstanding? My proposal was/is that the eight drivers have their traditional names, e.g. c64-lo.

**Comment by polluks** [comment]
I see. Maybe the name should depend who builds the driver?

**Comment by oliverschmidt** [comment]
Yep, therefore me referencing the c16/Plus4 joy driver sharing and the multiple Atari tgi driver sharing. There all that happens.

**Comment by polluks** [comment]
You cannot move/delete files in the browser... maybe I have to compile a git with TLS 1.2 myself.

**Comment by oliverschmidt** [comment]
> maybe I have to compile a git with TLS 1.2 myself.

Given the role GitHub plays in open source project hosting by now I'd say that any effort allowing you to fully participate is justified.

**Pull request closed without merging**
