### PR TITLE
ld65: give an error for multiply defined global symbols.

### LINKED ISSUE #878: Linker doesn't throw error for multiply defined symbols
Is there a reason that only a warning is generated? Other compilers (linkers) throw an error.

main.c:
```c
#include <stdio.h>
#ifdef __CC65__
#include <conio.h>
#endif

extern int testfun(void);

int main(void)
{
        printf("testfun returned %d\n", testfun());
#ifdef __CC65__
        cgetc();
#endif
        return 0;
}
```
t1.c:
```c
int testfun(void)
{
        return 1;
}
```
t2.c:
```c
int testfun(void)
{
        return 2;
}
```
compile:
```sh
$ cl65 -tatari -o t.com main.c t2.c t1.c 
ld65: Warning: Duplicate external identifier: '_testfun'
$ ls -l t.com
-rw-r--r--. 1 chris chris 3129 Apr 25 13:17 t.com
$ 
```

### PR DESCRIPTION
**Pull request by groessler**
Closes #878.

### CODE REVIEW

**Comment by oliverschmidt** [comment]
I personally like it this way. However, I'll give others some time to veto...

**Comment by greg-king5** [comment]
"ld65.sgml" needs to know about the new usage list.

**Comment by groessler** [comment]
Right. I've updated the PR.

**Comment by greg-king5** [comment]
:+1:

**Pull request merged**
