### PR TITLE
Split stdout and stderr in test/asm/

### PR DESCRIPTION
**Pull request by spiro-trikaliotis**
Some tests pipe the stdout and stderr of the compiler or assembler into a file and compare the result with a reference. This has the subtle problem that both stdout and stderr and buffered i/o streams that may or may not work the same on different OSs or even shells. That means the order of the lines in the resulting file is not guaranteed.

In practise it is "mostly" not an issue, but "we" still stumbled about one test where different behaviour can be triggered depending on running it in cmd.exe or bash (msys): test/asm/listing output of 010-paramcount.bin differs from the reference output when running the test from cmd.exe.

The solution is most likely to have two reference files and not redirect into one file.

This patch fixes the issue (cf. #1912) for the directory test/asm/.

### CODE REVIEW

**Comment by rofl0r** [comment]
commit title speaks of stdin where it should be stderr

**Comment by spiro-trikaliotis** [comment]
@rofl0r good catch... ;)

**Comment by spiro-trikaliotis** [comment]
@mrdudz Do you plan to comment on this PR, merge it, or doing anything else? I want to work on the assembler, but this PR is blocking me somehow - I have to rebase my work, and I do not want to do it twice, so I am waiting on the outcome of this PR...

**Comment by mrdudz** [comment]
i'll have a look and merge it in the next days (certainly weekend)... busy atm, sorry :)

**Pull request merged**
