### PR TITLE
Upload 64-bit Windows snapshot to Sourceforge

### PR DESCRIPTION
**Pull request by brian6932**
It would be nice to have a persistent snapshot binary upload for 64bit as well

### CODE REVIEW

**Comment by brian6932** [comment]
Since Travis CI isn't used anymore, shouldn't the `Makefile.travis`, and `.travis.yml` files be deleted?

**Comment by mrdudz** [comment]
Since i prefer things being kept simple - what is the advantage of using the 64bit build over the 32bit build?

**Comment by brian6932** [comment]
Everyone has 64bit computers nowadays, so if one should exist, I think it should be 64bit. As someone who wants to make a persistent package for both 64bit and 32bit, it kinda breaks my ability to do so, if for whatever reason the repo doesn't get a commit in the last 30 days (That's the actions artifact expiration time). Since both snapshots are made anyway, I don't really see why not, not like it adds any complexity, and just improves the performance of the compiler for it's users.

**Comment by mrdudz** [comment]
> Since both snapshots are made anyway, I don't really see why not, not like it adds any complexity

Yes, i didn't see this. Added, thx :)

**Pull request merged**
