### PR TITLE
Added vic20 $a000-$bfff ram emd.

### PR DESCRIPTION
**Pull request by blackystardust**
Added vic20 $a000-$bfff ram emd.

### CODE REVIEW

**Comment by oliverschmidt** [comment]
Thanks :-)

Either you or "some pull request post processor" ;-) would need to add a brief description to https://github.com/cc65/cc65/blob/master/doc/vic20.sgml#L148 showing up in http://cc65.github.io/doc/vic20.html#ss5.2 (in the style of https://github.com/cc65/cc65/blob/master/doc/c64.sgml#L268 showing up in http://cc65.github.io/doc/c64.html#ss7.2).

**Comment by blackystardust** [comment]
Added vic20 emd documentation.

**Comment by oliverschmidt** [comment]
Thanks for adding the doc :-)

Unfortunately the doc build fails (see text `continuous-integration/travis-ci/pr — The Travis CI build failed`) with:

Processing file ../doc/vic20.sgml
nsgmls:<OSFD>0:150:6:E: document type does not allow element "TAG" here; assuming missing "DESCRIP" start-tag
nsgmls:<OSFD>0:155:6:E: document type does not allow element "SECT1" here
nsgmls:<OSFD>0:173:6:E: document type does not allow element "SECT1" here
nsgmls:<OSFD>0:178:6:E: document type does not allow element "SECT1" here
nsgmls:<OSFD>0:184:5:E: document type does not allow element "SECT" here
nsgmls:<OSFD>0:194:5:E: document type does not allow element "SECT" here
nsgmls:<OSFD>0:246:5:E: document type does not allow element "SECT" here
nsgmls:<OSFD>0:267:9:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:150:2: start tag was here
info-postASP: Entry "Limitations" has wrong depth 6

**Comment by blackystardust** [comment]
Fixed the documentation building issue.

**Pull request merged**
