### PR TITLE
[cc65] Fixed function declarations with parameters of incomplete types

### LINKED ISSUE #1167: [cc65] Function prototypes?
Besides the issue mentioned in #1142 and #1162, there are several other issues with function declarations in cc65:
```c
int f1(int (*)(char *), int (*)[]);
int f1(int (*)(), int (*)[3]);          /* BUG cause:  This simply replaces the previous function descriptor */
int f1(int (*)(int), int (*)[]);        /* BUG result: Compiles. Should be an error */

int f2(int (*)(), int (*)[3]);
int f2(int (*)(char *), int (*)[]);     /* BUG cause:  This simply replaces the previous function descriptor */
int f2(int (*)(char *), int (*)[2]);    /* BUG result: Compiles. Should be an error */

int f3(void);
volatile int f3(void);                  /* Question: Is this OK? */

void f4(int);
void f4(volatile int);                  /* Question: Is this OK? */
```
The second prototypes of `f1` and `f2` simply replace the previous ones.

### PR DESCRIPTION
**Pull request by acqn**
- Fixed #1167. Functions may have incomplete types in their declarations (https://github.com/cc65/cc65/issues/1167#issuecomment-670254608).
- Now it warns on type declarations in the parameter lists that are invisible out of the function declarations (to help avoid problems as in #1216).

(4/4) Pushed.

---
1167b (https://github.com/cc65/cc65/issues/1167#issuecomment-670254608) example:
```c
/* Note: new types declared inside a parameter list are local to the function and not visible outside */
struct S;
void foo(struct S);            /* BUG: should be OK, not "Size of type 'struct S' is unknown" */
void foo(struct S { int a; }); /* BUG: should be error *due to function type conflict* (#1168) */
void foo(struct S);            /* BUG: should be OK, not "Size of type 'struct S' is unknown" */
void bar(struct T);            /* BUG: should be OK, not "Size of type 'struct T' is unknown" */
void bar(struct T);            /* BUG: should conflict with the above (#1168), not be "Size of type 'struct T' is unknown" */
```

Before:
```
1167b.c(3): Error: Size of type 'struct S' is unknown
1167b.c(4): Error: Conflicting function types for 'foo'
1167b.c(5): Error: Size of type 'struct S' is unknown
1167b.c(6): Error: Size of type 'struct T' is unknown
1167b.c(7): Error: Size of type 'struct T' is unknown
1167b.c(7): Error: Conflicting function types for 'bar'
6 errors and 0 warnings generated.
```

After:
```
1167b.c(4): Warning: 'struct S' will be invisible out of this function
1167b.c(4): Error: Conflicting function types for 'foo'
1167b.c(6): Warning: 'struct T' will be invisible out of this function
1167b.c(7): Warning: 'struct T' will be invisible out of this function
1167b.c(7): Error: Conflicting function types for 'bar'
2 errors and 3 warnings generated.
```

### CODE REVIEW

**Comment by acqn** [comment]
Huh? How could it be possible that `commit A` failed, then `commit A` + `commit B` passed, but then `commit A + B` fails?

**Comment by acqn** [comment]
@oliverschmidt Is it CI bugged?

**Comment by acqn** [comment]
```
dbg/dbg.c(466): Error: Conflicting function types for 'DisplayPrompt'
dbg/dbg.c(466): Error: 'void (const char *)' vs 'void (const char *)'
dbg/dbg.c(1415): Error: Conflicting function types for 'Redraw'
dbg/dbg.c(1415): Error: 'void (char)' vs 'void (char)'
dbg/dbg.c(1431): Error: Conflicting function types for 'GetKeyUpdate'
dbg/dbg.c(1431): Error: 'char (void)' vs 'char (void)'
```
This makes no sense....

**Comment by oliverschmidt** [comment]
> Is it CI bugged?

Not that I'd know of...

**Comment by acqn** [comment]
The bug is caused by desynched branch works. At the time this branch was started, `void` was not treated as an incomplete type. When PR #1175 that changed `void` to be an incomplete type in 89176bae4895b7459a610baba1f9e0e5a7693805 that would break 37df4eb320108b5418876bd240151ba8534069be was merged, the work of fc5c0e2a726b7025d83f8eb3b79a071470dc52fd had already been merged in this branch which happened to be immune to the `void` category change. Thus this branch could only fail the lib build when 89176bae4895b7459a610baba1f9e0e5a7693805 meets 37df4eb320108b5418876bd240151ba8534069be.

**Comment by oliverschmidt** [comment]
No content-related feedback in four days -> merging...

**Pull request merged**
