### PR TITLE
Fix #2262: Make sure there's no branching after the sequence

### PR DESCRIPTION
**Pull request by colinleroy**
Also better check that arguments match.

### CODE REVIEW

**Comment by mrdudz** [comment]
Any idea how to craft a proper test for that bug? Would be really nice to have that :)

**Comment by colinleroy** [comment]
> Any idea how to craft a proper test for that bug? Would be really nice to have that :)

I couldn't reproduce it with any construct on the main branch, so not really :/ You could add one in the float branch, though?

**Comment by mrdudz** [comment]
I have found it because a test in the float branch broke :)

Working on a test using that inline asm snippet - will commit later

**Comment by mrdudz** [comment]
https://github.com/cc65/cc65/commit/b31a1c7c0c25de087e272c045eb2370a03856c93

cheers :)

**Comment by colinleroy** [comment]
Oh yeah that works too! Thanks!

**Comment by mrdudz** [comment]
There should probably more of this kind of tests for the optimizer ... :)

**Pull request merged**
