### PR TITLE
Implementation of 8x8 and 16x16 booth multiplication for discussion

### PR DESCRIPTION
**Pull request by prandeamus**

### CODE REVIEW

**Comment by prandeamus** [comment]
As per issue #544, 8x8 booth multiply implementation for discussion.

**Comment by prandeamus** [comment]
@spiro-trikaliotis for you!

**Comment by greg-king5** [comment]
<cc65.h> declares functions that will give a better comparison between current cc65 code and your Booth implementations.

**Comment by prandeamus** [comment]
Thanks @greg-king5 I'll take a look.

**Comment by prandeamus** [comment]
I've established that the booth algorithm for 8x8->16 bit multiply works, but is slower than the existing code. It's possible that the booth 16x16->32 code can still be optimised, but right now it's just an academic curiosity.

I'm going to close this pull request for now but I will return to my branch some time and see if it can be improved. Code is still available on my fork if anyone is interested.

**Comment by oliverschmidt** [comment]
Thanks for the explanation.

**Comment by spiro-trikaliotis** [comment]
I am sorry that I did not have time yet to have a closer look into your implementation. However, it seems your implementation is not faster than the "school's method", and I am not surprised about this. Years ago, I came to the same conclusion, that it should not be possible to be faster on the 6502 for such small multiplications.

**Comment by prandeamus** [comment]
Well, it was good practice in re-learning 6502 assembly! Booth will only be more efficient if additional code that is required to detect runs of 1s and 0s is offset by fewer addition/subtractions. There's a chance that I can optimise the 16x16 case to get it closer to school method. I guess that the tipping point might be at 32x32->16 bits ... Thanks for your input, though, it was helpful.

**Pull request closed without merging**
