### PR TITLE
kindof hacky implementation of what was requested in issue #650

### PR DESCRIPTION
**Pull request by mrdudz**
This is a somewhat naive implementation of what was requested in issue #650

After doing this, i have to say i dont really like it, and the behaviour feels strange to me. It is already a significant amount of code for (imho) very little gain. I'd propose a classic "NMI lock" instead (which simple disables run/stop+restore)

Problems with this implementation:
- it fails with anything that banks out the kernal (for whatever reason). To handle this correctly a second nmi handler is needed that handles those NMIs slightly different (ie not chain to the system NMI). not sure how to implement this in a generic way.
- it will probably behave unexpected with anything that uses a custom NMI (rs232 drivers are the classic example).
- unsure how it will behave when a kernal NMI is needed (kernal rs232)
- exit code will always be -1 when exiting with runstop/restore
- on exit it prints "break in 816", probably some kernal flag needs to be cleared to supress this

As said, i find the whole behaviour kindof weird, i'd expect runstop/restore to either do a basic warmstart - or nothing at all. (and since re-running the program will not work for most non trivial programs, i dont really see the point either)

oh well, here it is :)

### CODE REVIEW

**Comment by oliverschmidt** [comment]
First of all thanks for the effort :-)

Just to recapture: I said that this functionality would be desirable because of e.g. closing files. Then you said, that this is done anyway. Then I mentioned `atexit()`. So at this point we sort of agrred that the functionality would be at least somewhat desirable. So far we didn't touch the question, how well it can be implemented in the first place.

Now you bring up - from my very limited CBM knowledge POV very substantial - reasons to rather not implement this functionality. I can follow your reasoning well and am open to closing my issue. It's basically up to you (and mybe other CBM gurus around) to decide...

**Comment by mrdudz** [comment]
Please dont call me guru =D

From my point of view its not really worth the effort. It CAN be implemented correctly (working in all cases), but this will require significantly more effort and code space.

The strongest argument hower to me is, that no matter what we do, its not possible to re-run most programs anyway, so whats the point of doing all this?

And yes, the normal system NMI handler does a BASIC warm start, which closes all files, initializes I/O and some other things.

**Comment by oliverschmidt** [comment]
The ability to re-run a program is from my POV pretty much unrelated to proposed feature. To me it is desirable as it allows to do all cleanup steps that may be necessary. I'm primarily thinking about avoiding file system inconsistencies or dangling IRQ pointers. If the default NMI handler already takes care of those (and similiar) things, then the proposed feature is probably already (partly) implemented.

**Comment by greg-king5** [comment]
> ..., which closes all files, initializes I/O and some other things.

It closes all computer files.  It does nothing to disk units' files.  Basically, computer files are only metadata (the primary/secondary addresses that everybody read about recently) that tell the computer where to find "the real files".  STOP-RESTORE cancels that data.  The computer forgets; the drive files become orphans.  Write files that aren't closed properly are unterminated (like C strings without '\0').

If a user is lucky, and remembers about the difference between computer and drive files, then that one can tell _each_ drive's (separate) DOS to close its files.  ... (if the user remembers) ...

Therefore, an argument can be made for this kind of code.  It would remember for us.

**Comment by mrdudz** [comment]
> I'm primarily thinking about avoiding file system inconsistencies

The CBM DOS will produce so called "splat files" (not closed) if the files are not closed by explicitly sending CLOSE - neither the default NMI handler nor this implementation will prevent this. if you want this, then even more code needs to be added, ie an atexit handler that explicitly closes all open files. Again, i dont think its worth the effort - users wont expect this to work (nor does it work like this in any other program).

**Comment by mrdudz** [comment]
> The ability to re-run a program is from my POV pretty much unrelated to proposed feature. To me it is desirable as it allows to do all cleanup steps that may be necessary.

To me, it raises the question what the usecase for pressing runstop/restore is.

**Comment by oliverschmidt** [comment]
I think/thought it is: "Quit the currently running program and return to the BASIC prompt."

**Comment by mrdudz** [comment]
> I think/thought it is: "Quit the currently running program and return to the BASIC prompt."

But to do what? As mentioned before elsewhere - most C64 Programs can not be "shut down" like this, very few programs offer an explicit "exit" feature, and as a result most users will not expect this feature to exist. They will either powercycle or press the reset button - and programs that "force exit" on runstop/restore are mostly considered "unprofessional" (which is why many either disable this completely, or use it to restart the program). To me handling this looks like a very academical thing to do, with little relevance in practise (and as said before, handling it properly will be quite some effort).

Oh and... regarding those open files - when you'd exit the program in the middle of a file operation, you'd likely end up with a broken (incomplete) file anyway, regardless if its properly closed or not - so closing it doesnt really solve anything (unless you expect the program to be able to handle such incomplete files, which in turn most programs will not). Any "corruption" (as in splat files) can easily be fixed by using a "validate" DOS command - which again most users will be familiar with.

**Comment by mrdudz** [comment]
Another thought: perhaps instead of putting this code into crt0 this way, it would be a better idea to implement it seperately as signal handling. Then crt0 can simply disable (lock) NMI by default, and those who want to have such exit handling on run/stop restore can use a signal handler to do whatever needs to be done. Sounds more reasonable to me :)

**Comment by oliverschmidt** [comment]
Again, I'm not insisting on anything. Maybe it's really all about user expectation. On the Apple II, a user runs a program, exits the program, and runs another program. Instead of figuring out how to exit this and that program "cleanly", users tend to use the Reset key to "quickly" get back to the prompt. Maybe it's more of a Reset thing on the C64 too(?).
And regarding the files: Please note that I was talking about file __system__ inconsistencies, not file __content__ inconsistencies. But maybe that's just no issue on the C64...

**Comment by mrdudz** [comment]
> Instead of figuring out how to exit this and that program "cleanly", users tend to use the Reset key to "quickly" get back to the prompt. Maybe it's more of a Reset thing on the C64 too(?).

As said, most ppl will probably either powercycle or press reset - since most programs have no option to exit. This is even more true these days, where cartridges like 1541U or TC64 are commonly used to load software - there is simply no point in exiting to the BASIC prompt, you just enter the cartridge menu directly and load another program.

> Please note that I was talking about file system inconsistencies, not file content inconsistencies. But maybe that's just no issue on the C64...

Its no issue. The DOS has a builtin "validate" command which will clean up the filesystem from incomplete/not closed files, and nothing breaks if those "splat files" exist.

**Comment by oliverschmidt** [comment]
So if there are no objections I suggest that I close my issue.

@mrdudz: Again thanks for the effort you put into this PR - for the waste basket after all :-(

**Comment by polluks** [comment]
CBM simply has no ProDOS bye equivalent.

**Comment by oliverschmidt** [comment]
See https://github.com/cc65/cc65/pull/1515#issuecomment-846590551.

**Comment by mrdudz** [comment]
(incase someone is wondering, i am abusing open/closing the PR for triggering the github actions - since there is no way to do this manually

**Comment by greg-king5** [comment]
> (incase someone is wondering, i am abusing open/closing the PR for triggering the github actions - since there is no way to do this manually

If you click on a check's `Details` link, then you go to its log.  Above the log, on the right side, is a button that reruns the Github actions for that PR.

**Comment by mrdudz** [comment]
OOOH! Damn, didnt see this. Good to know :)

**Pull request closed without merging**
