### PR TITLE
debian: add minimal generic packaging

### PR DESCRIPTION
**Pull request by pmjdebruijn**
should build on almost any vaguely recent debian derived system using

dpkg-buildpackage -rfakeroot

### CODE REVIEW

**Comment by oliverschmidt** [comment]
> When he took over cc65, Oliver decided to completely remove such build systems from the repository.

Yep.

> That's why I set up a project on OpenSUSE build service which automatically builds cc65 packages whenever there is a commit on git HEAD.

In order to avoid a potential misunderstanding I'd like to point out that this effort was explicitly welcome by me - and supported by commits like:

https://github.com/cc65/cc65/commit/32daa3dd2b004759e379e296ff00478c934992e4
https://github.com/cc65/cc65/commit/e320fe3db8ddb316eeb5e68e9af9aef75dd71628
https://github.com/cc65/cc65/commit/180caeba0a954020879c2e3f1c2cb9bf848a6d6f

Therefore it's no surprise that the "official" cc65@GitHub web pages link to it: http://cc65.github.io/cc65/getting-started.html#GNU

**Comment by spiro-trikaliotis** [comment]
> In order to avoid a potential misunderstanding I'd like to point out that this effort was explicitly welcome by me - and supported by commits like:

Good point. Yes, I should have added that I worked closely together with Oliver, and I had his support! And I am sure I still have if I feel like I need a change.

**Comment by oliverschmidt** [comment]
I don't see me merging this. This aspect hasn't been touched for quite some time so let me repeat:

I try to maintain this repo as the single cc65 upstream repo. Things like packaging belong to other places referring to this repo. I'm willing to support those things - with resonable effort. I.e. the automatic OpenSUSE build is possible because I set up the push notification for this repo.

Note: I know that the Windows binaries are sort of an exception to what I just wrote ;-)

**Comment by oliverschmidt** [comment]
> I should have added that I worked closely together with Oliver, and I had his support!

Thanks :-)

> And I am sure I still have if I feel like I need a change.

Indeed.

If Pascal thinks there's still something to add I'd propose to either add a page to https://github.com/cc65/wiki/wiki#Host_platforms or extend the page https://github.com/cc65/wiki/wiki/GNU-Linux. I can provide write access to the Wiki if requested.

**Pull request closed without merging**
