### PR TITLE
[cc65] More preprocessor fixes

### LINKED ISSUE #760: Error when using macros as pragma arguments
When trying to compile the code below
```c
#define BANK "PRG0"

#pragma rodata-name(push, BANK)
```
I get this error:
```
Error: String literal expected
```

### LINKED ISSUE #1357: X Macros don't work with C preprocessor
I am trying to use the unspeakably-useful "X macro" idiom with cc65 but the preprocessor is producing completely incorrect output.

Here's an example; the following code:
```c
#define OPCODES(X) \
    X(PUSHNIL) \
    X(PUSHTRUE) \
    X(PUSHFALSE)

enum {
#define X(op) op,
OPCODES(X)
#undef X
    N_OPS
};
```
When preprocessed `cc65 -E test.c -o test.c.pre` produces:
```c
enum {
X #undef X };(PUSHNIL) };(PUSHTRUE) };(PUSHFALSE)
```
But it should produce something like this:
```c
enum {
PUSHNIL,
PUSHTRUE,
PUSHFALSE,
    N_OPS
};
```

### LINKED ISSUE #1643: Very odd (wrong) error message
test.c containing just two lines:
```
#include <conio.h>
#include <string.h> 
```
and then compile like
```
$ cc65 -t geos-apple geosapple.c
geosapple.c:8: Error: Include file '(*(unsigned*)0x53).h' not found
1 errors and 0 warnings generated.
```
now isn't that one interesting? :)

### LINKED ISSUE #1787: cc65: Wrong line number in error message
This code:

```C
#define x       3
#define f(a)    f(x * (a))
#undef  x
#define x       2
#define g       f
#define z       z[0]
#define h       g(~
#define m(a)    a(w)
#define w       0,1
#define t(a)    a
#define p()     int
#define q(x)    x
#define r(x,y)  x ## y
#define str(x)  # x

f(y+1) + f(f(z)) % t(t(g) (0) + t)(1);
g(x+(3,4)-w) | h 5) & m(f)^m(m);
p() i[q()] = { q(1), r(2,3), r(4,), r(,5), r(,) };
char c[2][6] = { str(hello), str() };
```

when translated with "cc65 -E test.c" generates an error message with an invalid line number:

```
test.c(0): Error: Macro argument count mismatch
```

The resulting preprocessed output is also wrong, but this is probably not worth mentioning since the preprocessor doesn't have a problem, it *is* a problem :grinning: 

Maybe someone could at least fix the not very helpful line number in the message.

### LINKED ISSUE #1804: C preprocessor questions about included files
I failed to figure out whether standard C allows this:
```c
/* Main source file */

/* Q1: Is this OK? */
#include "h1.h"
/* to pair with the #if in "h1.h" */
#endif

/* Q2: Is this OK? */
#include "h2.h"
/* to pair with the left parenthesis in "h1.h" */
)
```
```c
/* File "h1.h" */
#if 1
/* no terminating #endif */
```
```c
/* File "h2.h" */
#define F()
F(
/* no terminating right parenthesis */
```
While GCC/Clang/MSVC all reject the code above, I can't find any standard text forbidding this. Did I miss anything?

### PR DESCRIPTION
**Pull request by acqn**
- [X] Most of preprocess directives may now be used between the pair of parentheses of function-like macro invocation. The one exception is `#pragma` that will be diagnosed with such usage.
- [X] Resolved #760. Macro expansion in `#pragma` works.
- [X] Fixed #1357. Macro expansion is improved but _not standard-conformant yet_ (to be addressed in later PRs).
- [X] Resolved #1643. If following a `#include` directive (not as the result of some macro expansion), a filename *directly enclosed* in `<>` or `""` is never macro-expanded. Note however, that if the token enclosed in `<>` or `""` is a result of macro expansion, it is still subject to further macro expansion as permitted by the the standard.
- [X] Resolved #1787 as regards to the very error message line number bug in the thread topic. The macro expansion result in the example is not correct yet.
- [X] Resolved #1804. Preprocessor now completes a run for every included file. Therefore `#if`/`#undef` and macro call parentheses etc. must be paired in the same file.
- [X] Fixed checking for extra `#endif`, which didn't always work.
- [X] Added warning on unterminated `'` and `"` for the preprocessor.
- [X] Fixed extra "Macro argument count mismatch" message when a macro argument list is unterminated.
- [X] Added warning on extra tokens at the end of directives.
- [X] Improved diagnostics on missing/illegal macro names.
- [X] Improved formatting of output with compiler option `-E`. Note that `#line` is not supported yet (but it will be in later PRs).
- [X] Predefined `__STDC_NO_ATOMICS__`, `__STDC_NO_COMPLEX__`, `__STDC_NO_THREADS__` and `__STDC_NO_VLA__` to `1` when compiling in `cc65` mode.

### CODE REVIEW

**Comment by acqn** [comment]
I like how test/misc and test/todo reminds me everytime.

**Comment by acqn** [comment]
I've made more fixes/improvements to the preprocessor. Shall I add the new changes to this PR?

**Comment by mrdudz** [comment]
will work on this next (add more tests perhaps).... please have patience, the heat is killing me :(

**Comment by mrdudz** [comment]
> Predefined __STDC_NO_ATOMICS__, __STDC_NO_COMPLEX__, __STDC_NO_THREADS__ and __STDC_NO_VLA__ to 1 when compiling in cc65 mode.

That should probably be mentioned in the documentation (cc65.html predefined macros)

**Comment by mrdudz** [comment]
merging this. It would still be nice to have more tests - however i dont want to block further fixes just because of that. thanks!

**Pull request merged**
