### PR TITLE
[cc65] Fixes for some OptStackOps bugs

### PR DESCRIPTION
**Pull request by acqn**
Fixed Issues #167 and #784 (= #1045 ?).
It also inlines some TOS functions like it used to do in cc65 v2.13.3 (#781).

### CODE REVIEW

**Comment by oliverschmidt** [comment]
First of all thanks for your quick help when it was asked for!

As stated (too) many times, the compiler in general and the optimizer in particular are a black box to me :-(

So what I'm left to notice is that both the coding style as well as the type of comments blend perfectly with the existing code base :-)

In https://github.com/cc65/cc65/issues/1045 you wrote _"the new fixes depend on some other stuff that I haven't fininished (and no way to finish anytime soon). So, do you want some seemingly random piles of commits that happen to fix this"_. Is this PR that "seemingly random pile of commits"?

If yes: Can you describe in a few sentences what that "other stuff that I haven't fininished (and no way to finish anytime soon)" is? If yes: Do you think it would be useful to persist that info somehow somewhere? Maybe at https://github.com/cc65/wiki/wiki/Roadmap ? Or maybe in comment(s) in the source code?

**Comment by acqn** [comment]
Well, this PR is at the middle ground. It consists of some selected old commits with some updates so that it can work.
I made a fork of cc65/ld65 with some arbitary hacks for my personal hobby 6502 project. Most were optimization enhancements, some were bug fixes and some were just specialized workflow features. The optimiztion enhancements worked for my project (and passed the tests, of course), but they lack broad and in-depth tests and I'm pretty sure that there are issues within them.
Since that project has been impacted and could be abandoned anytime thanks to the _change of daily life_, the hacks might never got cleaned up and reach the public.

**Comment by greg-king5** [comment]
`test/misc/cc65141011.c` should be moved to `test/val/` instead of `test/ref/`.  (It doesn't create output that would need to be compared to a reference file.)

**Comment by acqn** [comment]
> 
> 
> `test/misc/cc65141011.c` should be moved to `test/val/` instead of `test/ref/`. (It doesn't create output that would need to be compared to a reference file.)

Is it OK to just append a new commit to move that file?

**Comment by greg-king5** [comment]
> Is it OK to just append a new commit to move that file?

It worked. :tada:

**Comment by mrdudz** [comment]
i checked with the testcase of my bug report #1045 ... iterating to all combinations of options, without this patch it looks like this:

~~~
bug1045.g.6502.prg - ok
bug1045.O.6502.prg - fail
bug1045.Os.6502.prg - fail
bug1045.Osi.6502.prg - ok
bug1045.Osir.6502.prg - ok
bug1045.Osr.6502.prg - fail
bug1045.Oi.6502.prg - ok
bug1045.Oir.6502.prg - ok
bug1045.Or.6502.prg - fail
bug1045.g.65c02.prg - ok
bug1045.O.65c02.prg - fail
bug1045.Os.65c02.prg - fail
bug1045.Osi.65c02.prg - ok
bug1045.Osir.65c02.prg - ok
bug1045.Osr.65c02.prg - fail
bug1045.Oi.65c02.prg - ok
bug1045.Oir.65c02.prg - ok
bug1045.Or.65c02.prg - fail
bug1045.g.6502.cs.prg - ok
bug1045.O.6502.cs.prg - fail
bug1045.Os.6502.cs.prg - fail
bug1045.Osi.6502.cs.prg - fail
bug1045.Osir.6502.cs.prg - fail
bug1045.Osr.6502.cs.prg - fail
bug1045.Oi.6502.cs.prg - fail
bug1045.Oir.6502.cs.prg - fail
bug1045.Or.6502.cs.prg - fail
bug1045.g.65c02.cs.prg - ok
bug1045.O.65c02.cs.prg - fail
bug1045.Os.65c02.cs.prg - fail
bug1045.Osi.65c02.cs.prg - fail
bug1045.Osir.65c02.cs.prg - fail
bug1045.Osr.65c02.cs.prg - fail
bug1045.Oi.65c02.cs.prg - fail
bug1045.Oir.65c02.cs.prg - fail
bug1045.Or.65c02.cs.prg - fail
~~~

WITH this patch... they all work.

**Comment by mrdudz** [comment]
Updated the zip with some more variants of the test. They show various fails without this patch - and all work with the patch.

**Comment by oliverschmidt** [comment]
@acqn: Thanks for the detailed explanation.

@mrdudz: Thanks for conducting the test.

@greg-king5: Thanks for the review.

Merging...

**Comment by mrdudz** [comment]
don't forget to drop those tests into the test directory :)

**Comment by oliverschmidt** [comment]
@mrdudz: Can you take care of adding the test?

**Comment by mrdudz** [comment]
done, i hope i didnt screw anything up, git and me hate each other equally :)

**Comment by oliverschmidt** [comment]
> done

:-)

> i hope i didnt screw anything up, git and me hate each other equally :)

At least Travis CI seems happy: https://travis-ci.org/github/cc65/cc65/builds/701068122

**Pull request merged**
