### PR TITLE
Vc20 asm cfg + C64 PETSCII conversion include

### PR DESCRIPTION
**Pull request by skeetor**
I added the include file again, as this seemed to be undisputed in the discussion about screen code conversion.

### CODE REVIEW

**Comment by polluks** [comment]
So you want to close #838? At least take a look at my comment.

**Comment by skeetor** [comment]
This needs further investigation.

**Comment by mrdudz** [comment]
you should make seperate pull requests for seperate issues. this vic20 config is totally unrelated to the petscii stuff

**Comment by skeetor** [comment]
Yeah! Sorry about that. I'm not really used to github. :o

 

When I opened the PR I didn't epexct that it would also include the VIC-20 change as well, as there is already a seperate PR for that one. Didn't know how I properly resolve this, so I closed that PR. It needs some updates anyway. So currently only the VIC-20 PR is open. But does that mean, that I can not create a new PR later on, with different changes, as long as the older PR is still open?

 
I guess I have to create a development branch on my master, and then merge only stuff into the master, which should get promoted to the cc65 build, right?
 


Gesendet: Dienstag, 29. Januar 2019 um 13:24 Uhr
Von: "Bob Andrews" <notifications@github.com>
An: cc65/cc65 <cc65@noreply.github.com>
Cc: skeetor <sparhawk@gmx.at>, "State change" <state_change@noreply.github.com>
Betreff: Re: [cc65/cc65] Vc20 asm cfg + C64 PETSCII conversion include (#839)


you should make seperate pull requests for seperate issues. this vic20 config is totally unrelated to the petscii stuff

**Comment by silverdr** [comment]
@skeetor Read information on "gitflow". This applies not only to github. The typical way is to keep master in sync with the upstream and do all the development in feature branches. "Feature" - as opposed to "development". These are short-living branches that get deleted once the feature is accepted into upstream master. You create PRs from those branches.

**Comment by silverdr** [comment]
Oliver is the boss here so it's up to him to say. I personally think he might be much more forgiving the first time ;-) But for the future and in general it's best for all involved parties to get used to the expected worfklow.

**Comment by greg-king5** [comment]
This PR came from `skeetor/cc65:vc20-asm-cfg`.  That is a feature branch.  PR #838 should have come from there.

**Comment by oliverschmidt** [comment]
I see two options:

* There's a pull request only containing include/c64_screenmap.h, either by modifying this pull request or by creating another one.
* I create an include/c64_screenmap.h from scratch using the code proposed here.

Please chose an option and let me know.

**Comment by oliverschmidt** [comment]
As there was no feedback whatsoever :-( I went for the second option: https://github.com/cc65/cc65/commit/10a31d006b7fe230a2cd2a233ba86e05618beec4

**Pull request closed without merging**
