### PR TITLE
[cc65] Fixed predefined __FILE__, __LINE__ and added missing preprocessing directive #line

### LINKED ISSUE #1573: __LINE__ macro seems to not work, at least not with concatenation operator
Trying to use a static assertion macro to check things at compile time e.g. array sizes. It uses __LINE__ and the ## concat operator to generate a unique typename. 

```
#define CASSERT(predicate, file) _impl_CASSERT_LINE(predicate,__LINE__,file)

#define _impl_PASTE(a,b) a##b
#define _impl_CASSERT_LINE(predicate, line, file) \
    typedef char _impl_PASTE(assertion_failed_##file##_,line)[2*!!(predicate)-1];
```
    
For some reason __LINE__ doesn't get evaluated, though it's in the list of preprocessor supported macros...

> $ make
> cl65 -t cx16 -O hello.c character.c d6radix.c dice.c memory.c text.s
> character.c:18: Error: Size of array 'assertion_failed_character_c___LINE__' is invalid
> 1 errors and 0 warnings generated.
> make: *** [Makefile:2: hello] Error 1

### PR DESCRIPTION
**Pull request by acqn**
- [X] Fixed #1573. Fixed `__FILE__` and `__LINE__`.
- [X] Added mising `#line` preprocessing directive support. Surprise?

### CODE REVIEW

**Comment by acqn** [comment]
Huh? Something is different with GCC...

**Comment by mrdudz** [comment]
> Could the build check be configured to show more details (QUIET=0)?

In cases like this you could do it yourself in the PR (edit .github/workflows/build-on-pull-request.yml) - however, in this case it wouldnt help:

```
../../bin/cc65 -t sim6502  --add-source -Or -o ../../testwrk/val/bug1573.Or.6502.s bug1573.c 
../../bin/ca65 -t sim6502 -o ../../testwrk/val/bug1573.Or.6502.o ../../testwrk/val/bug1573.Or.6502.s 
../../bin/ld65 -t sim6502 -o ../../testwrk/val/bug1573.Or.6502.prg ../../testwrk/val/bug1573.Or.6502.o sim6502.lib 
../../bin/sim65 -x 5000000000 -c ../../testwrk/val/bug1573.Or.6502.prg > ../../testwrk/val/../../testwrk/val/bug1573.Or.6502.prg.out
make[2]: *** [Makefile:62: ../../testwrk/val/bug1573.Or.6502.prg] Fehler 1
```
so it actually produces a binary, but it fails:
```
$ ../../bin/sim65 -x 5000000000 -c ../../testwrk/val/bug1573.Or.6502.prg
Expected line1: 3, got: 21
Failures: 1
25569 cycles
```
(I'll have a look if/how the makefile could "cat" the result to the console so you see it in the CI too)

**Comment by mrdudz** [comment]
this also fails:
```
../../bin/cc65 -t sim65c02  --add-source -Osir -o ../../testwrk/val/bug1573.Osir.65c02.s bug1573.c 
../../bin/ca65 -t sim65c02 -o ../../testwrk/val/bug1573.Osir.65c02.o ../../testwrk/val/bug1573.Osir.65c02.s 
../../bin/ld65 -t sim65c02 -o ../../testwrk/val/bug1573.Osir.65c02.prg ../../testwrk/val/bug1573.Osir.65c02.o sim65c02.lib 
../../bin/sim65 -x 5000000000 -c ../../testwrk/val/bug1573.Osir.65c02.prg > ../../testwrk/val/../../testwrk/val/bug1573.Osir.65c02.prg.out
Expected line2: 30, got: 227
Failures: 1
27294 cycles
```

**Comment by mrdudz** [comment]
OK, it shows the output now on failure - hope that helps

**Comment by acqn** [comment]
> OK, it shows the output now on failure - hope that helps

Thanks. I think I've got it: a `StrBuf` const buf not terminated with a `\0`.

**Comment by mrdudz** [comment]
looks good to me - merging. thanks!

**Pull request merged**
