### PR TITLE
Add test case for #1332

### PR DESCRIPTION
**Pull request by jmr**

### CODE REVIEW

**Comment by greg-king5** [comment]
This test case needs to be changed because the bug isn't in the varargs handling.

**Comment by jmr** [comment]
Is it in how the varargs functions are called? The only failures I've found so far involve varargs functions.

**Comment by greg-king5** [comment]
It has nothing to do with varargs.  In the original issue example, the first `if ()` test actually is broken; it worked by accident.  I'm creating a new example for that issue that shows what really is happening.  (I posted here just to stop Oliver from merging this PR too soon.)

**Comment by jmr** [comment]
I trimmed down the test cases, keeping one similar to yours and one similar to the original bug report.

**Comment by greg-king5** [comment]
OK, my fix passes this test.

**Pull request merged**
