### PR TITLE
 Added 2a03/2a07 and HuC6280 detection. 

### PR DESCRIPTION
**Pull request by blackystardust**
Added 2a03/2a07 and HuC6280 detection.

### CODE REVIEW

**Comment by oliverschmidt** [comment]
The predominant style for hex digits in cc65 is upper case. Afaik this is consistent at least in the shared code. It would be nice if this file would be adjusted either before merging or after merging...

**Comment by blackystardust** [comment]
ok, will fix, and will keep it in mind for future contributions.

**Comment by blackystardust** [comment]
Fixed the hex digit cases in my latest commit.

**Comment by oliverschmidt** [comment]
> ok, will fix, and will keep it in mind for future contributions.

I appreciate that :-)

**Pull request merged**
