### PR TITLE
Added ASM-CFG for VIC-20 and C128

### PR DESCRIPTION
**Pull request by skeetor**
I added a config file for the VIC-20 and the C128 to be used for asm only programming.

### CODE REVIEW

**Comment by mrdudz** [comment]
Why was this closed again?

**Comment by skeetor** [comment]
Because I accidently create a second PR. So I closed one of them.

**Comment by skeetor** [comment]
Not sure now, but I see two PRs?

**Comment by mrdudz** [comment]
oh, ok, didnt notice that :=)

**Pull request closed without merging**
