### PR TITLE
Fix Atari keyboard code for cursor up key

### PR DESCRIPTION
**Pull request by IrgendwerA8**

### CODE REVIEW

**Comment by groessler** [comment]
Test program?

**Comment by IrgendwerA8** [comment]
How?

**Comment by groessler** [comment]
A simple program in which one can "walk" around the screen with the cursor keys. Something like that....

**Comment by groessler** [comment]
Not required. But would be nice...

**Comment by oliverschmidt** [comment]
I'm no ATARI guy but it seems reasonable that KEY_SHIFT should not be part of KEY_UP. Therefore I'm going to merge...

**Pull request merged**
