### PR TITLE
[cc65] Fixed Opt_staxspidx

### LINKED ISSUE #1397: Incorrect Behavior Related to Opt_staxspidx
I'm getting unexpected results compiling the included test code with the -O flag.

With no optimization the program produces the expected output.
```
cc65 -t cx16 main.c

c: ff
p: 0xbbbb
```

With -O it produces unexpected output. The line `po->c = 0xff;` seems to have no effect.
```
cc65 -t cx16 -O main.c

c: 0
p: 0xbbbb
```

Disabling OptBoolTrans produces expected output.
```
cc65 -t cx16 -O --disable-opt OptBoolTrans main.c

c: ff
p: 0xbbbb
```
Here is the test code.

```c
#include <cx16.h>
#include <stdio.h>

struct data_t {
	unsigned char c;
	int *p;	
};

struct data_t data;

void f() {
	int i = 1;
	int *pa = (int *)0xaaaa;
	int *pb = (int *)0xbbbb;
	struct data_t *po = &data;
	
	po->p = (i == 0) ? pa : pb;
	po->c = 0xff;	
}

void main() {
	f();
	
	printf("c: %hhx\n", data.c);
	printf("p: %p\n", data.p);
}
```

### PR DESCRIPTION
**Pull request by acqn**
Fixed #1397.

### CODE REVIEW

**Comment by greg-king5** [comment]
`Opt_staxspidx()` inlines a runtime function.  It increases code size.  Therefore, it should be used by `-Oi` not by `-O`.

**Comment by acqn** [comment]
- It's an issue not close to what this PR aims to resolve.
- The current optimization mechanism doesn't allow to assign different code-size factors to "sub-steps", whereas `Opt_staxspidx` is a "sub-step" of `OptStackOps`. To enable that, more work is needed.

**Comment by oliverschmidt** [comment]
@greg-king5: Do you agree with @acqn's statement? Do you have objections to merging this PR?

**Comment by greg-king5** [comment]
My statement isn't meant to be fixed by this PR.  This simply is a convenient place to mention the bug because it allowed this PR's bug to be triggered by `-O` instead of `-Oi`.

I approve this PR. :+1:

**Comment by oliverschmidt** [comment]
@acqn: Thanks for the fix.

@greg-king5: Thanks for your feedback - and merging.

**Pull request merged**
