### PR TITLE
Add --debug-tables <filename> option and output struct fields

### PR DESCRIPTION
**Pull request by empathicqubit**
Add an option to output symbol table information to a file instead of stdout. Add struct field and function scoped symbol information to output. This is merely an example, and should probably be thought about more thoroughly.

#1556

### CODE REVIEW

**Comment by empathicqubit** [comment]
I've been using this for a little while in another project without any issues since the last force-push, so I think it's ready to be looked at, at least.

**Comment by mrdudz** [comment]
It'd really be great if you'd also add documentation for this switch, and the format of the info it produces

**Comment by empathicqubit** [comment]
Okay, I added the switch along with an example to cc65.html

**Comment by empathicqubit** [comment]
Is there anything further that needs to be done with this? I'm not sure what the test failure is, since I didn't really change the compile behavior, only added logging.

**Comment by mrdudz** [comment]
i think that is the test-fails-randomly issue that was fixed, i will close/reopen for a test

**Pull request merged**
