### PR TITLE
Adds support for 65el02

### PR DESCRIPTION
**Pull request by Phillip-May**
Adds support for the 65el02, the library is complete enough to run ascii.c

### CODE REVIEW

**Comment by mrdudz** [comment]
The changes/files in samples/ should probably be removed from the PR :)

(what IS a rpc8e ?)

**Comment by Phillip-May** [comment]
A virtual computer designed by Eloram, an emulator with source code is available here: http://bigfootinformatika.hu/65el02/

**Comment by oliverschmidt** [comment]
Before investing more effort into this PR, I pose the question if this target generally qualifies for inclusion into the cc65 main line.

In my personal opinion it rather does not. 1.) It's a purely virtual target. 2.) That virtual target is (too) obscure from my POV. As far as I understand it's an extension of an extension of a game.

To move forward I suggest a discussion on the cc65 mailoing list. If there should be a momentum for inclusion of this target into the cc65 main line, we need to start on the details. This PR is it stands is pretty far from mergable. Just a few aspects:

* No documentation whatsoever
* No consistent source code formatting
* Variable naming doesn't fit cc65 style
* Missing optimization (cgect() written in C)
* Conceptual issues (write() calling cputc())
* ...

**Comment by mrdudz** [comment]
> In my personal opinion it rather does not. 1.) It's a purely virtual target. 2.) That virtual target is (too) obscure from my POV.

agreed :)

**Comment by oliverschmidt** [comment]
@Phillip-May: Anyhow thanks for your interest to contribute to cc65 !

**Pull request closed without merging**
