### PR TITLE
Preserve the accu

### PR DESCRIPTION
**Pull request by polluks**

### CODE REVIEW

**Comment by oliverschmidt** [comment]
You lost me here. Where's the benefit in preserving the accu when https://github.com/cc65/wiki/wiki/Parameter-passing-and-calling-conventions states that it isn't preserved and (as you know at least as well as I know) about every existing C library function doesn't preserve it?

**Comment by mrdudz** [comment]
Nicer to use from asm code? :) And it's always good to see BIT used in real code =P

**Comment by oliverschmidt** [comment]
> And it's always good to see BIT used in real code =P

Here you go: https://github.com/cc65/cc65/blob/master/libsrc/apple2/crt0.s#L130-L131 ;-)

In fact I use it always for "hitting" soft switches in the Apple II where the pure access already triggers the desired functionality - just as a means of "documenting" that it's the access what it's all about.

From that perspective I'm fine with merging this change. I just wanted to know if there's something else I'm not aware of...

**Comment by polluks** [comment]
@oliverschmidt Indeed, it's just cosmetic.

**Pull request merged**
