### PR TITLE
Fix a 16-bit fetch-and-store cc65 optimizer bug.

### LINKED ISSUE #632: Compile wrong with -O -Cl
This simple function loads a little-endian ushort from a buffer:
```C
unsigned short int load_le_ushort(unsigned char* buffer)
{
	unsigned short int aResult = buffer[1];
	aResult<<=8;
	aResult|=buffer[0];
	return aResult;
}
```
Compiling with latest cc65 v 2.17 with optimization and static locals gives me wrong assembler in the bit shift zone:
```asm
	lda     #$00
	sta     L0002+1
;
; aResult<<=8;
;
	sta     L0002
	sta     L0002+1
;
```
Clearly, this will build a 0 (zero) value, that is wrong.

This is the entire assembler function
```asm
; ---------------------------------------------------------------
; unsigned short __near__ load_le_ushort (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_le_ushort: near

.segment	"BSS"

L0002:
	.res	2,$00

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; unsigned short int aResult = buffer[1];
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     L0002
	lda     #$00
	sta     L0002+1
;
; aResult<<=8;
;
	sta     L0002
	sta     L0002+1
;
; aResult|=buffer[0];
;
	jsr     push0
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     tosora0
	sta     L0002
	stx     L0002+1
;
; }
;
	jmp     incsp2

.endproc
```

### PR DESCRIPTION
**Pull request by greg-king5**
Fixes #632.

### CODE REVIEW

**Comment by oliverschmidt** [comment]
The Travis CI log contains:

```
ref/yaccdbg.O.6502.prg
make[1]: *** [../../testwrk/ref/yaccdbg.O.6502.prg] Error 1
```

**Comment by greg-king5** [comment]
Proof that the regression tests work. :smirk_cat:

I forgot that the old pattern might have a label.  I didn't move it to the beginning of the new pattern.

**Comment by oliverschmidt** [comment]
> Proof that the regression tests work. 😼

Yep, my thought was that it shows that the effort in automating the regression tests was effort well spent :-)

**Comment by greg-king5** [comment]
I think that it's time to merge this one.

**Comment by oliverschmidt** [comment]
Surely !

I just didn‘t notice that you fixed the issue that made Travis CI fail.

**Pull request merged**
