### PR TITLE
[LD65] Add bank number to `seg` entries in dbgfile

### PR DESCRIPTION
**Pull request by clydeshaffer**
For https://github.com/cc65/cc65/issues/2537

This PR adds the bank number to `seg` entries, appended as ",bank=%lu" if it exists.

Example:
```
seg	id=0,name="CODE",start=0x00C305,size=0x2394,addrsize=absolute,type=ro,oname="bin/game.gtr.bankFF",ooffs=773,bank=255
seg	id=1,name="RODATA",start=0x00E699,size=0x0020,addrsize=absolute,type=ro,oname="bin/game.gtr.bankFF",ooffs=9881,bank=255
seg	id=2,name="BSS",start=0x0004F9,size=0x0444,addrsize=absolute,type=rw
seg	id=3,name="DATA",start=0x000200,size=0x02F9,addrsize=absolute,type=rw,oname="bin/game.gtr.bankFF",ooffs=0
seg	id=4,name="ZEROPAGE",start=0x000000,size=0x001A,addrsize=zeropage,type=rw
seg	id=5,name="NULL",start=0x000000,size=0x0000,addrsize=absolute,type=rw
seg	id=6,name="gfx",start=0x008000,size=0x1615,addrsize=absolute,type=ro,oname="bin/game.gtr.bank83",ooffs=0,bank=131
seg	id=7,name="audio",start=0x008000,size=0x01E9,addrsize=absolute,type=ro,oname="bin/game.gtr.bank81",ooffs=0,bank=129
seg	id=8,name="font",start=0x008000,size=0x04A3,addrsize=absolute,type=ro,oname="bin/game.gtr.bank82",ooffs=0,bank=130
seg	id=9,name="VECTORS",start=0x00FFFA,size=0x0006,addrsize=absolute,type=ro,oname="bin/game.gtr.bankFF",ooffs=16378,bank=255
seg	id=10,name="STARTUP",start=0x00E6B9,size=0x00DC,addrsize=absolute,type=ro,oname="bin/game.gtr.bankFF",ooffs=9913,bank=255
seg	id=11,name="COMMON",start=0x008000,size=0x0618,addrsize=absolute,type=ro,oname="bin/game.gtr.bank80",ooffs=0,bank=128
seg	id=12,name="LOADERS",start=0x008000,size=0x001E,addrsize=absolute,type=ro,oname="bin/game.gtr.bankFD",ooffs=0,bank=253
seg	id=13,name="PROG0",start=0x008000,size=0x0064,addrsize=absolute,type=ro,oname="bin/game.gtr.bankFC",ooffs=0,bank=252
seg	id=14,name="ONCE",start=0x00C2F9,size=0x000C,addrsize=absolute,type=ro,oname="bin/game.gtr.bankFF",ooffs=761,bank=255
```

### CODE REVIEW

**Comment by kugelfuhr** [comment]
What about `src/dbginfo/dbginfo.c`?

According to the [wiki](https://github.com/cc65/wiki/wiki/Debug-info-overview) (and also [here](https://github.com/cc65/wiki/wiki/Debug-info-module)) the module should be able to read/parse the debug info and allows retrieving the data. Is this still true or is the module abandoned?

And what about the [information in the wiki](https://github.com/cc65/wiki/wiki/Debug-info-data)? I don't know if it is current, but it won't be when this PR is merged.

Finally, there's `src/dbginfo/dbgsh.c` which builds into a program that is able to browse through a debug info file on the command line. If this program can no longer read debug info files, it should better be removed.

**Comment by clydeshaffer** [comment]
I've updated the dbginfo module to support parsing the `bank` parameter, and the `dbgsh` test program to print a column with the bank values when the `show segment` command is given.

```
➜  bin git:(dbg_banknum) ✗ ./dbgsh load ../../gametank_sdk/build/sourcemap.dbg
File loaded successfully
dbgsh> show segment
  id    name            address  size   output file     offs   bank
---------------------------------------------------------------------------
   0    CODE            $00C309  $21E1  bin/game.gtr.bankFF$0309  255
   1    RODATA          $00E4EA  $0020  bin/game.gtr.bankFF$24EA  255
   2    BSS             $0004FD  $0435                  $0000    0
   3    DATA            $000200  $02FD  bin/game.gtr.bankFF$0000    0
   4    ZEROPAGE        $000000  $001A                  $0000    0
   5    NULL            $000000  $0000                  $0000    0
   6    font            $008000  $04A3  bin/game.gtr.bank81$0000  129
   7    VECTORS         $00FFFA  $0006  bin/game.gtr.bankFF$3FFA  255
   8    STARTUP         $00E50A  $00DC  bin/game.gtr.bankFF$250A  255
   9    COMMON          $008000  $0618  bin/game.gtr.bank80$0000  128
  10    LOADERS         $008000  $0005  bin/game.gtr.bankFD$0000  253
  11    PROG0           $008000  $0064  bin/game.gtr.bankFC$0000  252
  12    ONCE            $00C2FD  $000C  bin/game.gtr.bankFF$02FD  255
  ```

**Comment by nickgirardo** [comment]
Any thoughts/ updates on this? I would find this really useful!

**Comment by mrdudz** [comment]
The patch looks ok to me... But like @kugelfuhr said, it should come with an update to the documentation.

That said - i would prefer if the documentation would be reworked and moved into the regular documentation. (I can totally understand if you don't want to do this, but it would be great if you did)

**Comment by clydeshaffer** [comment]
I'd be happy to update the documentation but it looks like GitHub doesn't have any provision for making PRs on wikis so I'm a little stuck there regarding what I can do myself.

From my reading of the relevant wiki page it looks like it just needs this additional line:
```
diff --git a/Debug-info-data.mediawiki b/Debug-info-data.mediawiki
index 6431bd7..0a1f261 100644
--- a/Debug-info-data.mediawiki
+++ b/Debug-info-data.mediawiki
@@ -113,6 +113,8 @@ Each module has a main scope where all symbols live, that are specified outside
 | The name of the output file, this segment was written to (may be empty)
 |-
 | The offset of the segment in the output file (only if name not empty)
+|-
+| The bank number of the segment's memory area
 |}
```

I could also take a look at moving the information about the debug info into the regular documentation, either as an addition to the ld65 doc or as its own page. Though that feels like its own separate project.

**Comment by mrdudz** [comment]
> looks like GitHub doesn't have any provision for making PRs on wikis

Yeah - that's why using them was a bad idea in the first place, there is no easy way for people to contribute

However, if that one line really is all that is needed, fine - i'll add it in the wiki and merge this.

Please still consider making it part of the regular documentation :)

**Comment by clydeshaffer** [comment]
Much appreciated! I'll try to make time this week to take a look at the documentation stuff

**Pull request merged**
