### PR TITLE
Save two bytes again

### PR DESCRIPTION
**Pull request by polluks2**

### CODE REVIEW

**Review by mrdudz — CHANGES_REQUESTED** [review]
please add a comment that this is a BIT abs

**Comment by polluks2** [comment]
We are not very consistent, please take a look
````
$ grep \$2C\  * -ri
apple2/tgi/a2.hi.s:        .byte   $2C             ; BIT absolute
atari/bgcolor.s:        .byte   $2c     ; bit opcode, eats the next 2 bytes
atari/dosdetect.s:        .byte   $2C             ; BIT <abs>
atari/dosdetect.s:        .byte   $2C             ; BIT <abs>
atari/dosdetect.s:        .byte   $2C             ; BIT <abs>
atari/dosdetect.s:        .byte   $2C             ; BIT <abs>
atari/syschdir.s:        .byte   $2C             ; BIT <abs>
atari/mou/atrst.s:        .byte   $2c                     ; bit opcode, eats next 2 bytes
atari/exec.s:        .byte   $2C             ; bit opcode, eats the next 2 bytes
atari5200/joy/atr5200std.s:        .byte   $2C             ; bit opcode, eats the next 2 bytes
atmos/joy/atmos-ijk.s:        .byte   $2C             ; Skip next opcode
common/vsnprintf.s:        .byte   $2C             ;(bit $xxxx)
geos-common/drivers/fio_module.s:        .byte $2c               ; skip
vic20/tgi/vic20-hi.s:        .byte   $2C             ;(bit $1234)
````
````
$ grep \$2C$  * -ri
c128/tgi/c128-vdc.s:        .byte   $2c
c128/tgi/c128-vdc2.s:        .byte   $2c
c128/emd/c128-reu.s:        .byte   $2C
c128/emd/c128-vdc.s:        .byte   $2c
c64/acc_c64dtv_speed.s:        .byte   $2C
c64/acc_detect_c64dtv.s:        .byte   $2C
c64/emd/c64-reu.s:        .byte   $2C
c64/emd/c64-vdc.s:        .byte   $2c
geos-cbm/tgi/geos-tgi.s:        .byte $2c
geos-cbm/emd/geos-vdc.s:        .byte $2c
geos-cbm/disk/dio_stc.s:        .byte $2c
geos-cbm/disk/dio_cts.s:        .byte $2c
geos-common/conio/_scrsize.s:        .byte $2c
nes/tgi/nes-64-56-2.s:        .byte   $2c
````

**Comment by mrdudz** [comment]
perhaps - that doesnt mean you shouldnt add it though :)

**Comment by mrdudz** [comment]
obsoleted by #1637

**Pull request closed without merging**
