### PR TITLE
Fix MSVC build broken by #1058

### PR DESCRIPTION
**Pull request by jmr**
MSVC complains about unary negation of unsigned, but it's
intended.  Suppress the warning.

https://github.com/cc65/cc65/pull/1058#discussion_r451757967

"Tested" with godbolt.org.

### CODE REVIEW

**Comment by jmr** [comment]
@acqn

**Comment by acqn** [comment]
I think you can cast BitOffs to int and cast the result of the negation back to unsigned int to avoid the warning without using #pragma.

**Comment by jmr** [comment]
It's a bit surprising that the CI uses different settings than just typing `make`. 

Since this is just an overzealous MSVC warning, the pragma seems to be the most straightforward solution.  If a bunch of different compilers were complaining, I would definitely rewrite it.

If this way is strongly disliked, I could go with `(0 - BitOffs) % CHAR_BITS`.

**Comment by oliverschmidt** [comment]
> It's a bit surprising that the CI uses different settings than just typing make.

The CI wants to make sure that the code base stays warning free with the very gcc used by the CI.

The make wants to generate binaries with as many different gcc variants (and similar compilers) as reasonable.

> If this way is strongly disliked, I could go with (0 - BitOffs) % CHAR_BITS.

I strongly prefer that approach over the pragma.

**Comment by mrdudz** [comment]
> I strongly prefer that approach over the pragma.

+1 ... anything compiler specific should be avoided if possible. perhaps add a comment why it was done like this.

**Comment by jmr** [comment]
Done.

**Comment by oliverschmidt** [comment]
Thanks for adjusting the fix :-)

**Pull request merged**
