### PR TITLE
Add kbhit for Telestrat

### PR DESCRIPTION
**Pull request by jedeoric**
Hello,

Here is missing kbhit code for Telestrat

### CODE REVIEW

**Comment by oliverschmidt** [comment]
Every function intended to be called by C needs to set the X register on return, see https://github.com/cc65/wiki/wiki/Parameter-passing-and-calling-conventions

**Comment by jedeoric** [comment]
@oliverschmidt Fixed

**Comment by polluks** [comment]
What about `jmp return1` and `jmp return0` to save some bytes?

**Comment by groessler** [comment]
Better, put the "ldx #0" before the "bcs" and in "@no_char_action" do just a "txa; rts"

**Comment by jedeoric** [comment]
Fixed here : https://github.com/cc65/cc65/pull/1393

**Pull request merged**
